/* ══════════════════════════════════════════════════════════════
   Content expansion #2 — presentation variance + pool depth.

   Two jobs:
   1. Give high-traffic concepts several vignettes (classic / atypical
      / elderly / severe / mimic) so a concept that resurfaces for
      review shows a DIFFERENT patient — the same disease presents
      many ways. Variant items reuse an existing conceptId; no new
      concept entry is needed.
   2. Enlarge the ECG and Buzzword pools (they were ~= a set size, so
      every set looked identical) and add depth in thin subtopics.

   All UNREVIEWED, every vignette sourced. Synthetic patients only.
   ══════════════════════════════════════════════════════════════ */

import { v, type ContentModule, type RawConcept, type RawItem } from './authoring';
import type { System } from '../types';

/* New concepts only (variants of existing concepts need no entry). */
const concepts: RawConcept[] = [
  { conceptId: 'dka-recognition', name: 'Diabetic ketoacidosis', system: 'endocrine', topic: 'Diabetic emergencies' },

  /* ECG pool depth */
  { conceptId: 'ecg-sinus-brady', name: 'ECG: sinus bradycardia', system: 'cardiovascular', topic: 'ECG — rate' },
  { conceptId: 'ecg-sinus-tach', name: 'ECG: sinus tachycardia', system: 'cardiovascular', topic: 'ECG — rate' },
  { conceptId: 'ecg-svt', name: 'ECG: SVT (AVNRT)', system: 'cardiovascular', topic: 'ECG — narrow-complex' },
  { conceptId: 'ecg-junctional', name: 'ECG: junctional rhythm', system: 'cardiovascular', topic: 'ECG — narrow-complex' },
  { conceptId: 'ecg-bbb', name: 'ECG: bundle branch block', system: 'cardiovascular', topic: 'ECG — wide-complex' },

  /* Buzzword pool depth */
  { conceptId: 'assoc-heinz-g6pd', name: 'Heinz bodies → G6PD deficiency', system: 'heme_onc', topic: 'Buzzwords — heme/onc' },
  { conceptId: 'assoc-howell-jolly', name: 'Howell–Jolly bodies → asplenia', system: 'heme_onc', topic: 'Buzzwords — heme/onc' },
  { conceptId: 'assoc-basophilic-stippling', name: 'Basophilic stippling → lead', system: 'heme_onc', topic: 'Buzzwords — heme/onc' },
  { conceptId: 'assoc-anti-ttg', name: 'Anti-tTG → celiac disease', system: 'gi', topic: 'Buzzwords — GI/liver' },
  { conceptId: 'assoc-anti-centromere', name: 'Anti-centromere → limited scleroderma', system: 'msk_rheum', topic: 'Buzzwords — rheumatology' },
  { conceptId: 'assoc-anti-scl70', name: 'Anti-Scl-70 → diffuse scleroderma', system: 'msk_rheum', topic: 'Buzzwords — rheumatology' },
  { conceptId: 'assoc-anti-ro-la', name: 'Anti-Ro/La → Sjögren', system: 'msk_rheum', topic: 'Buzzwords — rheumatology' },
  { conceptId: 'assoc-negri', name: 'Negri bodies → rabies', system: 'infectious', topic: 'Buzzwords — infectious disease' },
  { conceptId: 'assoc-koplik', name: 'Koplik spots → measles', system: 'infectious', topic: 'Buzzwords — infectious disease' },
  { conceptId: 'assoc-slapped-cheek', name: 'Slapped cheek → parvovirus B19', system: 'infectious', topic: 'Buzzwords — infectious disease' },
  { conceptId: 'assoc-strawberry-tongue', name: 'Strawberry tongue → Kawasaki', system: 'cardiovascular', topic: 'Buzzwords — pediatrics' },
  { conceptId: 'assoc-currant-jelly-stool', name: 'Currant-jelly stool → intussusception', system: 'gi', topic: 'Buzzwords — pediatrics' },
  { conceptId: 'assoc-olive-mass', name: 'Olive mass → pyloric stenosis', system: 'gi', topic: 'Buzzwords — pediatrics' },
  { conceptId: 'assoc-boot-shaped-heart', name: 'Boot-shaped heart → Tetralogy of Fallot', system: 'cardiovascular', topic: 'Buzzwords — cardiology' },
  { conceptId: 'assoc-cherry-red-macula', name: 'Cherry-red macula → Tay–Sachs', system: 'neuro', topic: 'Buzzwords — neurology' },
  { conceptId: 'assoc-erythema-migrans', name: 'Target rash → Lyme disease', system: 'infectious', topic: 'Buzzwords — infectious disease' },
];

const subtopics: Record<string, string> = {
  'dka-recognition': 'endo.diabetes',
  'ecg-sinus-brady': 'cv.arrhythmia',
  'ecg-sinus-tach': 'cv.arrhythmia',
  'ecg-svt': 'cv.arrhythmia',
  'ecg-junctional': 'cv.arrhythmia',
  'ecg-bbb': 'cv.arrhythmia',
  'assoc-heinz-g6pd': 'heme.anemia',
  'assoc-howell-jolly': 'heme.anemia',
  'assoc-basophilic-stippling': 'heme.anemia',
  'assoc-anti-ttg': 'gi.nutrition',
  'assoc-anti-centromere': 'rheum.connective',
  'assoc-anti-scl70': 'rheum.connective',
  'assoc-anti-ro-la': 'rheum.connective',
  'assoc-negri': 'id.zoonotic',
  'assoc-koplik': 'id.respiratory-id',
  'assoc-slapped-cheek': 'id.respiratory-id',
  'assoc-strawberry-tongue': 'cv.congenital',
  'assoc-currant-jelly-stool': 'gi.lower',
  'assoc-olive-mass': 'gi.upper',
  'assoc-boot-shaped-heart': 'cv.congenital',
  'assoc-cherry-red-macula': 'neuro.neurocutaneous',
  'assoc-erythema-migrans': 'id.zoonotic',
};

const alsoSystems: Record<string, System[]> = {
  'assoc-strawberry-tongue': ['infectious'],
  'assoc-anti-ttg': ['msk_rheum'],
};

const items: RawItem[] = [
  /* ══════════ CARDIO — presentation variance ══════════ */
  {
    itemId: 'stemi-recognition-alt1', version: 1, type: 'one_liner', conceptId: 'stemi-recognition', presentation: 'classic',
    stem: '64 M with 30 minutes of crushing substernal pressure, diaphoresis, and nausea.',
    vitals: [v('HR', '52', true), v('BP', '108/70')],
    findings: ['ECG: ST elevation in II, III and aVF with reciprocal depression in I and aVL.'],
    options: [
      { id: 'a', text: 'Inferior STEMI', correct: true },
      { id: 'b', text: 'Anterior STEMI', whyNot: 'Anterior injury elevates V2–V4; the inferior leads II/III/aVF here localise to the inferior wall.' },
      { id: 'c', text: 'Pericarditis', whyNot: 'Pericarditis elevates ST diffusely with PR depression and no reciprocal change — this has reciprocal depression.' },
      { id: 'd', text: 'Early repolarization', whyNot: 'Benign early repolarization does not give reciprocal depression or this clinical picture.' },
    ],
    discriminator: 'Regional ST elevation in II, III and aVF with reciprocal depression is an inferior STEMI — the bradycardia hints at right-coronary territory and vagal tone.',
    teachingPoint: 'Get a right-sided lead: inferior STEMI with RV involvement is preload-dependent and nitrates can drop the pressure.',
    tags: { system: 'cardiovascular', complaint: 'chest pain', rotation: ['em', 'im'], level: 'both' },
    difficultySeed: 0.75, source: [{ ref: 'ACC/AHA Chest Pain Guideline', year: 2021 }],
  },
  {
    itemId: 'stemi-recognition-alt2', version: 1, type: 'one_liner', conceptId: 'stemi-recognition', presentation: 'elderly',
    stem: '83 F brought in confused and generally weak; family notes she "hasn\'t been herself" since this morning. No chest pain reported.',
    vitals: [v('HR', '104', true), v('BP', '112/68'), v('SpO₂', '94% RA')],
    findings: ['Diaphoretic and grey. ECG: ST elevation in V2–V5.'],
    options: [
      { id: 'a', text: 'Acute myocardial infarction', correct: true },
      { id: 'b', text: 'Urinary tract infection with delirium', whyNot: 'A UTI does not lift the ST segments; the ECG reframes the confusion as an anginal equivalent.' },
      { id: 'c', text: 'Dehydration', whyNot: 'Dehydration does not produce anterior ST elevation and diaphoretic pallor.' },
      { id: 'd', text: 'Transient ischemic attack', whyNot: 'A TIA gives focal neurologic deficits, not global weakness with an infarct pattern on ECG.' },
    ],
    discriminator: 'In the elderly, infarction often presents as confusion or weakness without chest pain — the ECG, not the story, makes the diagnosis, so get it early.',
    tags: { system: 'cardiovascular', complaint: 'confusion', rotation: ['em', 'im', 'fm'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'ACC/AHA Chest Pain Guideline', year: 2021 }],
  },
  {
    itemId: 'adhf-recognition-alt1', version: 1, type: 'one_liner', conceptId: 'adhf-recognition', presentation: 'elderly',
    stem: '80 M on a beta-blocker with several days of fatigue, poor appetite and abdominal fullness; his ankles are swollen and he sleeps in a recliner now.',
    vitals: [v('HR', '78'), v('BP', '138/82'), v('SpO₂', '93% RA', true)],
    findings: ['JVP elevated, tender hepatomegaly, 2+ pedal edema, bibasilar crackles.'],
    options: [
      { id: 'a', text: 'Decompensated heart failure', correct: true },
      { id: 'b', text: 'Cirrhosis with ascites', whyNot: 'Liver disease raises the abdomen but not the JVP; the elevated neck veins and orthopnea point to the heart.' },
      { id: 'c', text: 'Nephrotic syndrome', whyNot: 'Nephrotic edema is not accompanied by a raised JVP, crackles and an S3 of cardiac congestion.' },
      { id: 'd', text: 'COPD exacerbation', whyNot: 'COPD does not raise the JVP or produce hepatic congestion and orthopnea.' },
    ],
    discriminator: 'Right-sided congestion — raised JVP, tender hepatomegaly, edema — with a heart rate blunted by beta-blockade is decompensated heart failure presenting quietly in an elder.',
    tags: { system: 'cardiovascular', complaint: 'edema', rotation: ['im', 'fm'], level: 'both' },
    difficultySeed: 0.7, source: [{ ref: 'ACC/AHA/HFSA Heart Failure Guideline', year: 2022 }],
  },
  {
    itemId: 'vt-vs-svt-alt1', version: 1, type: 'one_liner', conceptId: 'vt-vs-svt', presentation: 'severe',
    stem: '66 M with dilated cardiomyopathy, now with palpitations and near-syncope; the monitor shows a broad, regular tachycardia at 190 and he is becoming clammy.',
    vitals: [v('HR', '190', true), v('BP', '84/52', true)],
    findings: ['Wide monomorphic complexes, no discernible P waves; fusion beats seen.'],
    options: [
      { id: 'a', text: 'Ventricular tachycardia', correct: true },
      { id: 'b', text: 'SVT with aberrancy', whyNot: 'Fusion beats and a structurally abnormal heart make VT the answer; misclassifying it risks a lethal drug choice.' },
      { id: 'c', text: 'Sinus tachycardia', whyNot: 'Sinus tachycardia is narrow with visible P waves and rarely reaches 190 with fusion beats.' },
      { id: 'd', text: 'Atrial flutter with aberrancy', whyNot: 'Flutter would show sawtooth atrial activity; fusion beats and AV dissociation point to the ventricle.' },
    ],
    discriminator: 'A hemodynamically worsening wide regular tachycardia with fusion beats in a cardiomyopath is VT — instability means synchronized cardioversion now, not a diagnostic pause.',
    tags: { system: 'cardiovascular', complaint: 'palpitations', rotation: ['em', 'im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'AHA/ACC/HRS Ventricular Arrhythmias Guideline', year: 2017 }],
  },
  {
    itemId: 'tamponade-alt1', version: 1, type: 'one_liner', conceptId: 'tamponade', presentation: 'severe',
    stem: 'A stab wound to the left chest; the patient is hypotensive with distended neck veins and muffled heart sounds.',
    vitals: [v('HR', '132', true), v('BP', '80/60', true), v('Pulsus', '20 mmHg', true)],
    findings: ['Clear breath sounds bilaterally; FAST shows pericardial fluid.'],
    options: [
      { id: 'a', text: 'Cardiac tamponade', correct: true },
      { id: 'b', text: 'Tension pneumothorax', whyNot: 'Tension pneumothorax silences one lung and deviates the trachea; here breath sounds are clear and the pericardium holds fluid.' },
      { id: 'c', text: 'Hemorrhagic shock alone', whyNot: 'Pure hemorrhage lowers the JVP; the distended neck veins with hypotension are obstructive, not hypovolemic.' },
      { id: 'd', text: 'Myocardial contusion', whyNot: 'Contusion causes arrhythmia and wall-motion change, not Beck triad with pericardial fluid.' },
    ],
    discriminator: 'Beck triad — hypotension, distended neck veins and muffled heart sounds — with clear lungs after penetrating chest trauma is tamponade, relieved by pericardial decompression.',
    tags: { system: 'cardiovascular', complaint: 'shock', rotation: ['em', 'surg'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'ATLS 10th edition', year: 2018 }],
  },
  {
    itemId: 'dissection-alt1', version: 1, type: 'one_liner', conceptId: 'dissection-first', presentation: 'classic',
    stem: '58 M with Marfan features and abrupt tearing chest pain radiating between the shoulder blades; he looks unwell.',
    vitals: [v('BP R arm', '176/94', true), v('BP L arm', '132/78', true), v('HR', '104', true)],
    findings: ['Early diastolic murmur; CT angiography shows an intimal flap in the ascending aorta.'],
    options: [
      { id: 'a', text: 'Aortic dissection (type A)', correct: true },
      { id: 'b', text: 'Acute coronary syndrome', whyNot: 'ACS does not give an arm-to-arm pressure gap, a new regurgitant murmur or an intimal flap on CT.' },
      { id: 'c', text: 'Pulmonary embolism', whyNot: 'PE causes pleuritic pain and hypoxia, not tearing interscapular pain with a pressure differential.' },
      { id: 'd', text: 'Musculoskeletal back strain', whyNot: 'Strain does not produce a pulse deficit, aortic regurgitation or an unwell appearance.' },
    ],
    discriminator: 'Tearing interscapular pain with an inter-arm pressure gap and aortic regurgitation in a connective-tissue phenotype is a proximal dissection — a surgical emergency, and anticoagulation is contraindicated.',
    tags: { system: 'cardiovascular', complaint: 'chest pain', rotation: ['em', 'surg'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'ACC/AHA Aortic Disease Guideline', year: 2022 }],
  },

  /* ══════════ PULM — presentation variance ══════════ */
  {
    itemId: 'pe-recognition-alt1', version: 1, type: 'one_liner', conceptId: 'pe-recognition', presentation: 'elderly',
    stem: '84 F brought in after a fall, now confused, with no chest pain; the only consistent finding is that she is breathing fast.',
    vitals: [v('HR', '104', true), v('RR', '26', true), v('SpO₂', '90% RA', true), v('BP', '128/76')],
    findings: ['Lungs clear. Left calf mildly swollen. ECG: sinus tachycardia.'],
    options: [
      { id: 'a', text: 'Pulmonary embolism', correct: true },
      { id: 'b', text: 'Pneumonia', whyNot: 'The chest is clear and there is no fever or productive cough; unexplained tachypnea and hypoxemia point to the circulation.' },
      { id: 'c', text: 'Mechanical fall with confusion', whyNot: 'A fall does not lower the oxygen saturation; the hypoxemia and tachypnea demand a cardiopulmonary cause.' },
      { id: 'd', text: 'Urinary tract infection', whyNot: 'A UTI does not produce hypoxemia with a clear chest and a swollen calf.' },
    ],
    discriminator: 'In the elderly, PE often shows only tachypnea, hypoxemia or an unexplained fall — a clear chest with a low saturation should still make you think clot, not confusion.',
    tags: { system: 'pulmonary', complaint: 'confusion', rotation: ['em', 'im', 'fm'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'ESC Guidelines on Acute Pulmonary Embolism', year: 2019 }],
  },
  {
    itemId: 'pe-recognition-alt2', version: 1, type: 'one_liner', conceptId: 'pe-recognition', presentation: 'atypical',
    stem: '55 M with a single episode of syncope and now persistent unexplained sinus tachycardia; he feels short of breath on standing.',
    vitals: [v('HR', '116', true), v('SpO₂', '92% RA', true), v('BP', '104/70')],
    findings: ['Clear chest. ECG: sinus tachycardia with an S1Q3T3 pattern; right heart strain on echo.'],
    options: [
      { id: 'a', text: 'Pulmonary embolism', correct: true },
      { id: 'b', text: 'Vasovagal syncope', whyNot: 'Vasovagal syncope resolves with recovery and does not leave persistent tachycardia, hypoxemia and RV strain.' },
      { id: 'c', text: 'Arrhythmia', whyNot: 'The rhythm is sinus; the tachycardia is compensating for a large clot, not a primary arrhythmia.' },
      { id: 'd', text: 'Anxiety', whyNot: 'Anxiety cannot explain hypoxemia or echocardiographic right heart strain.' },
    ],
    discriminator: 'Syncope with persistent unexplained tachycardia, hypoxemia and RV strain is a large PE — the syncope reflects a transient drop in cardiac output across the clot.',
    tags: { system: 'pulmonary', complaint: 'syncope', rotation: ['em', 'im'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'ESC Guidelines on Acute Pulmonary Embolism', year: 2019 }],
  },
  {
    itemId: 'cap-recognition-mimic1', version: 1, type: 'one_liner', conceptId: 'cap-recognition', presentation: 'mimic',
    stem: 'Post-op day 5 after knee surgery with pleuritic chest pain and dyspnea — but also fever to 39°C, a productive cough, and focal findings at the right base.',
    vitals: [v('T', '39.0', true), v('HR', '104', true), v('RR', '24', true), v('SpO₂', '92% RA', true)],
    findings: ['Bronchial breathing and crackles at the right base with egophony; CXR: right lower lobe consolidation.'],
    options: [
      { id: 'a', text: 'Postoperative pneumonia', correct: true },
      { id: 'b', text: 'Pulmonary embolism', whyNot: 'The post-op setting screams PE, but fever with focal consolidation and egophony is infection — PE leaves the chest clear.' },
      { id: 'c', text: 'Atelectasis', whyNot: 'Atelectasis gives low-grade fever without dense consolidation, bronchial breathing and egophony.' },
      { id: 'd', text: 'Aspiration pneumonitis', whyNot: 'Chemical pneumonitis follows a witnessed aspiration and is more diffuse; a lobar consolidation with egophony is bacterial pneumonia.' },
    ],
    discriminator: 'This looks like the classic post-op PE, but fever with lobar consolidation and egophony makes it pneumonia — the lung exam is the discriminator that PE would leave normal.',
    teachingPoint: 'The highest-value skill is resisting the reflex: the same post-op story can be clot or infection, and the chest exam decides.',
    tags: { system: 'pulmonary', complaint: 'chest pain', rotation: ['im', 'surg'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'ATS/IDSA Community-acquired Pneumonia Guideline', year: 2019 }],
  },
  {
    itemId: 'cap-recognition-alt1', version: 1, type: 'one_liner', conceptId: 'cap-recognition', presentation: 'atypical',
    stem: '21 F college student with a week of low-grade fever, malaise, headache and a dry hacking cough; she looks better than her chest X-ray, which shows patchy bilateral interstitial infiltrates.',
    vitals: [v('T', '37.9', true), v('HR', '92'), v('SpO₂', '96% RA')],
    findings: ['Scattered crackles; cold agglutinins positive.'],
    options: [
      { id: 'a', text: 'Atypical (walking) pneumonia — Mycoplasma', correct: true },
      { id: 'b', text: 'Lobar pneumococcal pneumonia', whyNot: 'Pneumococcus gives a toxic patient with lobar consolidation and rusty sputum, not a well-appearing student with diffuse interstitial infiltrates.' },
      { id: 'c', text: 'Acute bronchitis', whyNot: 'Bronchitis does not produce infiltrates on chest film or positive cold agglutinins.' },
      { id: 'd', text: 'Influenza alone', whyNot: 'Flu can precede it, but the persisting dry cough with interstitial infiltrates and cold agglutinins is Mycoplasma.' },
    ],
    discriminator: 'A young patient looking better than a diffusely abnormal film, with a dry cough and cold agglutinins, is atypical (Mycoplasma) pneumonia — the exam–imaging mismatch is the clue.',
    tags: { system: 'pulmonary', complaint: 'cough', rotation: ['fm', 'im'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'ATS/IDSA Community-acquired Pneumonia Guideline', year: 2019 }],
  },
  {
    itemId: 'copd-hf-alt1', version: 1, type: 'one_liner', conceptId: 'copd-vs-hf', presentation: 'classic',
    stem: '68 M with a 50-pack-year history, increased sputum that has turned purulent, and worsening wheeze and breathlessness over three days; no orthopnea or edema.',
    vitals: [v('HR', '98'), v('RR', '24', true), v('SpO₂', '88% RA', true)],
    findings: ['Diffuse wheeze and prolonged expiration; JVP normal, no S3, no edema. BNP normal.'],
    options: [
      { id: 'a', text: 'COPD exacerbation', correct: true },
      { id: 'b', text: 'Decompensated heart failure', whyNot: 'A normal JVP, no S3, no edema and a normal BNP argue against congestion; the picture is airways, not pump.' },
      { id: 'c', text: 'Pulmonary embolism', whyNot: 'PE gives sudden dyspnea with a clear chest, not three days of purulent sputum and wheeze.' },
      { id: 'd', text: 'Pneumonia', whyNot: 'No fever, no focal consolidation — this is a diffuse airflow-obstruction flare, not a lobar infection.' },
    ],
    discriminator: 'Increased purulent sputum with diffuse wheeze and a normal JVP/BNP is a COPD exacerbation — the absence of congestion signs separates it from the cardiac mimic.',
    tags: { system: 'pulmonary', complaint: 'dyspnea', rotation: ['im', 'em', 'fm'], level: 'both' },
    difficultySeed: 0.7, source: [{ ref: 'GOLD Report on COPD', year: 2024 }],
  },

  /* ══════════ NEURO — presentation variance ══════════ */
  {
    itemId: 'ischemic-stroke-alt1', version: 1, type: 'one_liner', conceptId: 'ischemic-stroke', presentation: 'atypical',
    stem: '70 F with sudden vertigo, vomiting, double vision and difficulty walking; she cannot sit up without falling to one side.',
    vitals: [v('BP', '168/90', true)],
    findings: ['Nystagmus, dysmetria, truncal ataxia; limb strength normal. CT head negative for blood.'],
    options: [
      { id: 'a', text: 'Posterior circulation (cerebellar) stroke', correct: true },
      { id: 'b', text: 'Benign peripheral vertigo (BPPV)', whyNot: 'BPPV is brief and positional with a normal gait; truncal ataxia and diplopia signal a central posterior stroke.' },
      { id: 'c', text: 'Vestibular neuritis', whyNot: 'Neuritis gives isolated vertigo with an abnormal head-impulse test, not diplopia, dysmetria and inability to walk.' },
      { id: 'd', text: 'Migraine', whyNot: 'Sudden persistent ataxia and diplopia in an elderly hypertensive is a stroke until imaging clears the posterior fossa.' },
    ],
    discriminator: 'Sudden vertigo with diplopia, ataxia and inability to walk is a posterior-circulation stroke — central signs and gait failure separate it from a peripheral cause.',
    teachingPoint: 'CT is poor for the posterior fossa; MRI is needed, and the HINTS exam can outperform early imaging.',
    tags: { system: 'neuro', complaint: 'vertigo', rotation: ['em', 'neur'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'AHA/ASA Acute Ischemic Stroke Guideline', year: 2019 }],
  },
  {
    itemId: 'bacterial-meningitis-alt1', version: 1, type: 'one_liner', conceptId: 'bacterial-meningitis', presentation: 'severe',
    stem: '19 M college student with hours of fever, severe headache and neck stiffness, now with a rapidly spreading non-blanching petechial rash and hypotension.',
    vitals: [v('T', '39.6', true), v('HR', '128', true), v('BP', '88/50', true)],
    findings: ['Photophobia, Kernig sign positive; purpuric rash on the trunk and limbs.'],
    options: [
      { id: 'a', text: 'Meningococcal meningitis with sepsis', correct: true },
      { id: 'b', text: 'Viral meningitis', whyNot: 'Viral meningitis is not accompanied by a purpuric rash and septic shock — the petechiae point to meningococcemia.' },
      { id: 'c', text: 'Rocky Mountain spotted fever', whyNot: 'RMSF rash starts on wrists/ankles after a tick bite; fulminant meningism with purpura in a dorm is meningococcus.' },
      { id: 'd', text: 'Immune thrombocytopenia', whyNot: 'ITP causes bleeding without fever, meningism or shock.' },
    ],
    discriminator: 'Fever and meningism with a rapidly spreading non-blanching petechial rash is meningococcal disease — the purpura marks bloodstream invasion and demands antibiotics within the hour.',
    tags: { system: 'neuro', complaint: 'fever & rash', rotation: ['em', 'im'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'IDSA Bacterial Meningitis Guidelines', year: 2004 }],
  },
  {
    itemId: 'parkinson-mimic1', version: 1, type: 'discriminator', conceptId: 'parkinson', presentation: 'mimic',
    stem: 'A patient on a dopamine-blocking antiemetic develops symmetric bradykinesia and rigidity over weeks. Which feature best distinguishes drug-induced parkinsonism from Parkinson disease?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Symmetric onset with a clear temporal link to the drug', correct: true },
      { id: 'b', text: 'A resting tremor', whyNot: 'Both can tremor; the symmetry and drug timing, not the tremor, separate them.' },
      { id: 'c', text: 'Cogwheel rigidity', whyNot: 'Rigidity occurs in both — it does not discriminate cause.' },
      { id: 'd', text: 'Response to levodopa', whyNot: 'Levodopa response is variable in drug-induced cases and does not cleanly separate them; the drug history does.' },
    ],
    discriminator: 'Symmetric parkinsonism that begins after a dopamine-blocking drug is drug-induced and often reversible — idiopathic Parkinson disease is asymmetric and progressive.',
    tags: { system: 'neuro', complaint: 'tremor', rotation: ['neur', 'psych', 'im'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'MDS Clinical Diagnostic Criteria for Parkinson Disease', year: 2015 }],
  },
  {
    itemId: 'myasthenia-crisis-alt1', version: 1, type: 'cant_miss', conceptId: 'myasthenia-gravis', presentation: 'severe',
    stem: 'A myasthenic with a recent infection now has a weak cough, difficulty swallowing and a falling forced vital capacity. What must you watch for and act on?',
    vitals: [v('FVC', 'falling', true), v('RR', '26', true)],
    findings: ['Weak neck flexion, nasal speech, unable to clear secretions.'],
    options: [
      { id: 'a', text: 'Myasthenic crisis — impending respiratory failure', correct: true },
      { id: 'b', text: 'Simple fatigue', whyNot: 'Bulbar weakness with a falling vital capacity is not ordinary fatigue — it is neuromuscular respiratory failure in evolution.' },
      { id: 'c', text: 'Anxiety hyperventilation', whyNot: 'Anxiety does not weaken the cough and swallow or drop the FVC; the danger here is airway loss.' },
      { id: 'd', text: 'Pneumonia alone', whyNot: 'Infection may be the trigger, but the acute threat is bulbar and respiratory muscle failure needing airway support.' },
    ],
    discriminator: 'A myasthenic with bulbar weakness and a falling vital capacity is in crisis — monitor the FVC and secure the airway before the gas goes bad, then treat with IVIG or plasma exchange.',
    tags: { system: 'neuro', complaint: 'weakness', rotation: ['neur', 'em', 'im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'International Consensus Guidance for Management of MG', year: 2021 }],
  },

  /* ══════════ RENAL / GI / ENDO / MSK — variance ══════════ */
  {
    itemId: 'nephrolithiasis-alt1', version: 1, type: 'cant_miss', conceptId: 'nephrolithiasis', presentation: 'severe',
    stem: 'A patient with a known ureteric stone now has a high fever, rigors and hypotension. What does this combination demand?',
    vitals: [v('T', '39.3', true), v('HR', '118', true), v('BP', '90/56', true)],
    findings: ['CT: obstructing stone with hydronephrosis; pyuria.'],
    options: [
      { id: 'a', text: 'Emergent urological decompression of the obstructed, infected system', correct: true },
      { id: 'b', text: 'Oral antibiotics and analgesia at home', whyNot: 'An obstructed, infected kidney is a urological emergency — pus under pressure needs drainage, not outpatient care.' },
      { id: 'c', text: 'Wait for the stone to pass', whyNot: 'Waiting with an infected obstruction risks urosepsis and kidney loss.' },
      { id: 'd', text: 'Increase fluids only', whyNot: 'Fluids alone do not relieve an obstructed, infected collecting system.' },
    ],
    discriminator: 'Fever and sepsis behind an obstructing stone is pyonephrosis — an emergency for decompression (stent or nephrostomy) plus antibiotics, because obstruction turns infection into a surgical problem.',
    tags: { system: 'renal', complaint: 'flank pain & fever', rotation: ['em', 'surg', 'im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'AUA Guideline on Surgical Management of Stones', year: 2016 }],
  },
  {
    itemId: 'ain-alt1', version: 1, type: 'one_liner', conceptId: 'ain', presentation: 'atypical',
    stem: 'A patient on a long-term proton pump inhibitor is found to have a subacute rise in creatinine, with sterile pyuria and mild subnephrotic proteinuria, but no rash or fever.',
    vitals: [v('Cr', '2.2', true)], findings: ['Urine white cells without bacteria; renal biopsy shows interstitial inflammation.'],
    options: [
      { id: 'a', text: 'Acute interstitial nephritis (PPI-induced)', correct: true },
      { id: 'b', text: 'Chronic kidney disease progression', whyNot: 'A subacute rise with sterile pyuria and interstitial inflammation on biopsy is an active nephritis, not slow CKD.' },
      { id: 'c', text: 'Prerenal azotemia', whyNot: 'Prerenal disease has a bland sediment; sterile pyuria with interstitial inflammation is AIN.' },
      { id: 'd', text: 'Diabetic nephropathy', whyNot: 'Diabetic disease is bland heavy proteinuria over years, not a drug-linked interstitial nephritis.' },
    ],
    discriminator: 'AIN can present without the classic triad — a PPI (or other drug) with a subacute creatinine rise and sterile pyuria is enough; the eosinophils and rash are often absent.',
    tags: { system: 'renal', complaint: 'AKI', rotation: ['im'], level: 'clerkship' },
    difficultySeed: 0.55, source: [{ ref: 'KDIGO AKI Guideline', year: 2012 }],
  },
  {
    itemId: 'appendicitis-alt1', version: 1, type: 'one_liner', conceptId: 'appendicitis', presentation: 'atypical',
    stem: '25 M with two days of vague right-sided and back discomfort, low-grade fever and some diarrhea; abdominal tenderness is deep and poorly localised.',
    vitals: [v('T', '37.9', true), v('HR', '96')],
    findings: ['Pain on rectal exam to the right; CT shows a retrocecal appendicitis.'],
    options: [
      { id: 'a', text: 'Retrocecal appendicitis', correct: true },
      { id: 'b', text: 'Gastroenteritis', whyNot: 'Diarrhea can mislead, but focal right-sided tenderness on rectal exam and CT findings make this an atypically located appendicitis.' },
      { id: 'c', text: 'Ureteric colic', whyNot: 'Colic is severe and radiates to the groin with hematuria, not a smouldering deep ache with fever.' },
      { id: 'd', text: 'Inflammatory bowel disease', whyNot: 'IBD is chronic with bloody diarrhea and systemic features, not an acute retrocecal inflammatory mass.' },
    ],
    discriminator: 'A retrocecal appendix can present with vague pain, diarrhea and few anterior signs — the diagnosis hides, so atypical right-sided pain with fever still earns imaging.',
    tags: { system: 'gi', complaint: 'abdominal pain', rotation: ['surg', 'em'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'WSES Jerusalem Guidelines for Acute Appendicitis', year: 2020 }],
  },
  {
    itemId: 'cholecystitis-alt1', version: 1, type: 'one_liner', conceptId: 'cholecystitis', presentation: 'atypical',
    stem: 'A critically ill, fasting ICU patient on total parenteral nutrition develops fever and right-upper-quadrant tenderness with a rising white count.',
    vitals: [v('T', '38.6', true), v('HR', '110', true)],
    findings: ['Ultrasound: distended, thick-walled gallbladder with sludge but no stones.'],
    options: [
      { id: 'a', text: 'Acalculous cholecystitis', correct: true },
      { id: 'b', text: 'Calculous cholecystitis', whyNot: 'There are no stones; in a fasting critically ill patient, gallbladder stasis inflames it without calculi.' },
      { id: 'c', text: 'Ventilator-associated pneumonia', whyNot: 'VAP does not localise to the right upper quadrant or thicken the gallbladder wall.' },
      { id: 'd', text: 'C. difficile colitis', whyNot: 'C. diff causes diarrhea and colonic wall thickening, not RUQ gallbladder inflammation.' },
    ],
    discriminator: 'Fever and RUQ signs with a thick-walled, sludge-filled but stone-free gallbladder in a fasting ICU patient is acalculous cholecystitis — stasis, not a stone, is the culprit.',
    tags: { system: 'gi', complaint: 'RUQ pain', rotation: ['surg', 'im'], level: 'clerkship' },
    difficultySeed: 0.55, source: [{ ref: 'Tokyo Guidelines for Acute Cholecystitis', year: 2018 }],
  },
  {
    itemId: 'dka-recognition-1', version: 1, type: 'one_liner', conceptId: 'dka-recognition', presentation: 'classic',
    stem: '19 F type 1 diabetic with a day of vomiting, abdominal pain, deep rapid breathing and a fruity odour on the breath, after skipping insulin during a flu.',
    vitals: [v('HR', '118', true), v('RR', '28', true), v('Glucose', '480', true)],
    findings: ['Dry mucous membranes; ketones in urine and blood; pH 7.15 with a high anion gap.'],
    options: [
      { id: 'a', text: 'Diabetic ketoacidosis', correct: true },
      { id: 'b', text: 'Hyperosmolar hyperglycemic state', whyNot: 'HHS is the older type-2 picture with very high glucose, minimal ketones and a near-normal pH — this young type-1 has ketoacidosis.' },
      { id: 'c', text: 'Gastroenteritis', whyNot: 'Vomiting can mislead, but Kussmaul breathing, ketones and a high-gap acidosis define DKA.' },
      { id: 'd', text: 'Salicylate toxicity', whyNot: 'Salicylates give tinnitus and a mixed acid–base picture without hyperglycemia and ketonuria.' },
    ],
    discriminator: 'Hyperglycemia with ketones and a high anion-gap acidosis in a type-1 diabetic who missed insulin is DKA — Kussmaul breathing and the fruity odour are the bedside signature.',
    tags: { system: 'endocrine', complaint: 'metabolic emergency', rotation: ['em', 'im', 'peds'], level: 'both' },
    difficultySeed: 0.85, source: [{ ref: 'ADA Standards of Care — Hyperglycemic Crises', year: 2024 }],
  },
  {
    itemId: 'graves-alt1', version: 1, type: 'one_liner', conceptId: 'graves', presentation: 'elderly',
    stem: '76 M with new atrial fibrillation, weight loss, apathy and proximal weakness; he seems withdrawn rather than agitated.',
    vitals: [v('HR', '124', true), v('BP', '150/70', true)],
    findings: ['Fine tremor; TSH undetectable with high free T4. Lid lag present.'],
    options: [
      { id: 'a', text: 'Apathetic hyperthyroidism', correct: true },
      { id: 'b', text: 'Depression', whyNot: 'Depression does not suppress TSH, raise free T4 or trigger new atrial fibrillation with a tremor.' },
      { id: 'c', text: 'Occult malignancy', whyNot: 'Weight loss can suggest cancer, but the suppressed TSH and high T4 point to thyrotoxicosis.' },
      { id: 'd', text: 'Heart failure', whyNot: 'The AF and weight loss here are driven by thyrotoxicosis, which the thyroid labs confirm.' },
    ],
    discriminator: 'In elders, thyrotoxicosis can present as apathy, weight loss and new atrial fibrillation rather than the classic hyperkinetic picture — check a TSH in unexplained new AF.',
    tags: { system: 'endocrine', complaint: 'weight loss', rotation: ['im', 'fm'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'ATA Guidelines for Hyperthyroidism', year: 2016 }],
  },
  {
    itemId: 'gout-alt1', version: 1, type: 'one_liner', conceptId: 'gout', presentation: 'atypical',
    stem: 'An older man on a diuretic with chronic tophi now has a polyarticular flare involving several fingers and a knee, with low-grade fever.',
    vitals: [v('T', '37.8')], findings: ['Firm nodules over the joints and an ear; aspirate: needle-shaped, negatively birefringent crystals.'],
    options: [
      { id: 'a', text: 'Polyarticular tophaceous gout', correct: true },
      { id: 'b', text: 'Rheumatoid arthritis', whyNot: 'RA is a symmetric small-joint synovitis with anti-CCP, not urate crystals and tophi.' },
      { id: 'c', text: 'Septic arthritis', whyNot: 'Infection is a single hot joint with organisms; here multiple joints show urate crystals and no organisms.' },
      { id: 'd', text: 'Osteoarthritis flare', whyNot: 'OA is non-inflammatory without crystals, tophi or fever.' },
    ],
    discriminator: 'Long-standing gout can go polyarticular with tophi and mimic other arthritides — the negatively birefringent crystals still name it, even when the pattern is atypical.',
    tags: { system: 'msk_rheum', complaint: 'polyarthritis', rotation: ['im', 'fm'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'ACR Guideline for Management of Gout', year: 2020 }],
  },
  {
    itemId: 'septic-arthritis-alt1', version: 1, type: 'one_liner', conceptId: 'septic-arthritis', presentation: 'atypical',
    stem: 'A sexually active 24 F with a few days of migratory joint pains, tenosynovitis of the wrist, pustular skin lesions and now a hot swollen knee.',
    vitals: [v('T', '38.4', true)], findings: ['Pustules on the extremities; knee aspirate with high neutrophils.'],
    options: [
      { id: 'a', text: 'Disseminated gonococcal arthritis', correct: true },
      { id: 'b', text: 'Reactive arthritis', whyNot: 'Reactive arthritis follows GI/GU infection with conjunctivitis and urethritis but not pustular skin lesions and tenosynovitis of gonococcemia.' },
      { id: 'c', text: 'Rheumatoid arthritis', whyNot: 'RA is a chronic symmetric synovitis, not an acute migratory picture with pustules and fever.' },
      { id: 'd', text: 'Gout', whyNot: 'Gout is crystal-driven monoarthritis without migratory pustular skin lesions and tenosynovitis.' },
    ],
    discriminator: 'Migratory arthralgia, tenosynovitis and pustular skin lesions in a young sexually active adult is disseminated gonococcal infection — a distinctive triad that other septic arthritides lack.',
    tags: { system: 'msk_rheum', complaint: 'polyarthritis', rotation: ['im', 'em'], level: 'clerkship' },
    difficultySeed: 0.55, source: [{ ref: 'CDC Sexually Transmitted Infections Treatment Guidelines', year: 2021 }],
  },

  /* ══════════ ECG — pool depth ══════════ */
  {
    itemId: 'ecg-sinus-brady-1', version: 1, type: 'ecg', conceptId: 'ecg-sinus-brady',
    stem: 'A fit young athlete, asymptomatic. Read the strip.',
    vitals: [], findings: [],
    ecg: { rate: 44, regularity: 'regular', pWave: 'normal', qrsWide: false, lead: 'Lead II' },
    options: [
      { id: 'a', text: 'Sinus bradycardia', correct: true },
      { id: 'b', text: 'Complete heart block', whyNot: 'Complete block dissociates P from QRS; here each QRS follows a normal upright P.' },
      { id: 'c', text: 'Junctional rhythm', whyNot: 'A junctional escape lacks preceding P waves; this rhythm has a normal P before every QRS.' },
      { id: 'd', text: 'Atrial fibrillation', whyNot: 'AF is irregular with no P waves; this is slow but regular with clear P waves.' },
    ],
    discriminator: 'A slow, regular rhythm with a normal P before every QRS is sinus bradycardia — often physiologic in the athletic or sleeping patient.',
    tags: { system: 'cardiovascular', complaint: 'bradycardia', rotation: ['im', 'fm'], level: 'both' },
    difficultySeed: 0.8, source: [{ ref: 'ACC/AHA/HRS Bradycardia Guideline', year: 2018 }],
  },
  {
    itemId: 'ecg-sinus-tach-1', version: 1, type: 'ecg', conceptId: 'ecg-sinus-tach',
    stem: 'A febrile, dehydrated patient. Read the strip.',
    vitals: [], findings: [],
    ecg: { rate: 122, regularity: 'regular', pWave: 'normal', qrsWide: false, lead: 'Lead II' },
    options: [
      { id: 'a', text: 'Sinus tachycardia', correct: true },
      { id: 'b', text: 'SVT (AVNRT)', whyNot: 'AVNRT is faster (150–220) with buried or absent P waves; here an upright P precedes each QRS at a physiologic rate.' },
      { id: 'c', text: 'Atrial flutter', whyNot: 'Flutter shows sawtooth waves, not a discrete upright P before each QRS.' },
      { id: 'd', text: 'Ventricular tachycardia', whyNot: 'VT is wide and P-less; this is narrow with normal P waves.' },
    ],
    discriminator: 'A narrow, regular tachycardia with an upright P before every QRS is sinus tachycardia — treat the cause (fever, pain, hypovolemia, hypoxia), not the rate.',
    tags: { system: 'cardiovascular', complaint: 'tachycardia', rotation: ['im', 'em'], level: 'both' },
    difficultySeed: 0.8, source: [{ ref: 'ACC/AHA/HRS SVT Guideline', year: 2015 }],
  },
  {
    itemId: 'ecg-svt-1', version: 1, type: 'ecg', conceptId: 'ecg-svt',
    stem: 'Sudden palpitations in a young woman, abrupt onset. Read the strip.',
    vitals: [], findings: [],
    ecg: { rate: 190, regularity: 'regular', pWave: 'absent', qrsWide: false, lead: 'Lead II' },
    options: [
      { id: 'a', text: 'Supraventricular tachycardia (AVNRT)', correct: true },
      { id: 'b', text: 'Ventricular tachycardia', whyNot: 'VT is a wide-complex rhythm; this narrow regular tachycardia arises above the ventricles.' },
      { id: 'c', text: 'Sinus tachycardia', whyNot: 'Sinus tachycardia has visible P waves and rarely starts and stops abruptly at 190.' },
      { id: 'd', text: 'Atrial fibrillation', whyNot: 'AF is irregularly irregular; AVNRT is metronome-regular with no discernible P waves.' },
    ],
    discriminator: 'A narrow, regular tachycardia near 180–200 with no visible P waves and abrupt onset is AVNRT — vagal maneuvers or adenosine are first-line.',
    tags: { system: 'cardiovascular', complaint: 'palpitations', rotation: ['em', 'im'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'ACC/AHA/HRS SVT Guideline', year: 2015 }],
  },
  {
    itemId: 'ecg-junctional-1', version: 1, type: 'ecg', conceptId: 'ecg-junctional',
    stem: 'A patient on digoxin with lightheadedness. Read the strip.',
    vitals: [], findings: [],
    ecg: { rate: 46, regularity: 'regular', pWave: 'absent', qrsWide: false, lead: 'Lead II' },
    options: [
      { id: 'a', text: 'Junctional escape rhythm', correct: true },
      { id: 'b', text: 'Sinus bradycardia', whyNot: 'Sinus bradycardia keeps an upright P before each QRS; a junctional rhythm has no preceding P.' },
      { id: 'c', text: 'Complete heart block', whyNot: 'Complete block shows dissociated P waves marching independently; here there are no P waves at all.' },
      { id: 'd', text: 'Atrial fibrillation', whyNot: 'AF is irregular with a fibrillatory baseline; this is slow, regular and narrow without P waves.' },
    ],
    discriminator: 'A slow, regular, narrow rhythm with no P waves is a junctional escape — the AV junction takes over when the sinus node fails or is suppressed.',
    tags: { system: 'cardiovascular', complaint: 'bradycardia', rotation: ['im', 'em'], level: 'clerkship' },
    difficultySeed: 0.55, source: [{ ref: 'ACC/AHA/HRS Bradycardia Guideline', year: 2018 }],
  },
  {
    itemId: 'ecg-bbb-1', version: 1, type: 'ecg', conceptId: 'ecg-bbb',
    stem: 'Incidental finding on a pre-operative ECG, asymptomatic. Read the strip.',
    vitals: [], findings: [],
    ecg: { rate: 78, regularity: 'regular', pWave: 'normal', qrsWide: true, lead: 'Lead II' },
    options: [
      { id: 'a', text: 'Bundle branch block', correct: true },
      { id: 'b', text: 'Ventricular tachycardia', whyNot: 'VT is fast and P-less; this is a normal-rate sinus rhythm with a P before every wide QRS.' },
      { id: 'c', text: 'Pre-excitation (WPW)', whyNot: 'WPW shortens the PR and slurs the upstroke with a delta wave; BBB keeps a normal PR without a delta.' },
      { id: 'd', text: 'Hyperkalemia', whyNot: 'Hyperkalemia widens the QRS but adds peaked T waves and flattening P waves; here the P waves and T waves are normal.' },
    ],
    discriminator: 'A wide QRS at a normal rate with a normal P before each complex and a normal PR is a bundle branch block — the preserved P–QRS relationship separates it from VT.',
    tags: { system: 'cardiovascular', complaint: 'incidental', rotation: ['im', 'fm'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'AHA/ACCF/HRS Recommendations for ECG Interpretation', year: 2009 }],
  },
  {
    itemId: 'ecg-afib-alt1', version: 1, type: 'ecg', conceptId: 'ecg-afib',
    stem: 'A rate-controlled patient with known atrial fibrillation, asymptomatic. Read the strip.',
    vitals: [], findings: [],
    ecg: { rate: 74, regularity: 'irregularly_irregular', pWave: 'fibrillatory', qrsWide: false, lead: 'Lead II' },
    options: [
      { id: 'a', text: 'Atrial fibrillation (rate-controlled)', correct: true },
      { id: 'b', text: 'Normal sinus rhythm', whyNot: 'Sinus rhythm is regular with clear P waves; this baseline wavers and the R–R intervals never settle.' },
      { id: 'c', text: 'Sinus arrhythmia', whyNot: 'Sinus arrhythmia keeps a P before each QRS and varies gently with breathing, not the P-less chaos of AF.' },
      { id: 'd', text: 'Atrial flutter', whyNot: 'Flutter marches a regular sawtooth; AF is irregularly irregular with a fibrillatory baseline.' },
    ],
    discriminator: 'AF is defined by rhythm, not rate — an irregularly irregular rhythm with no P waves is atrial fibrillation even when the ventricular rate is well controlled at 74.',
    tags: { system: 'cardiovascular', complaint: 'incidental', rotation: ['im', 'fm'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'ACC/AHA/ACCP/HRS Atrial Fibrillation Guideline', year: 2023 }],
  },
  {
    itemId: 'ecg-stemi-alt1', version: 1, type: 'ecg', conceptId: 'ecg-stemi',
    stem: '59 F with an hour of chest pressure and nausea. Read the strip.',
    vitals: [], findings: [],
    ecg: { rate: 68, regularity: 'regular', pWave: 'normal', qrsWide: false, stShift: 0.5, tWave: 'normal', lead: 'Lead III' },
    options: [
      { id: 'a', text: 'ST-elevation myocardial infarction', correct: true },
      { id: 'b', text: 'Normal ECG', whyNot: 'The ST segments are lifted well off the baseline — that is exactly what a normal tracing excludes.' },
      { id: 'c', text: 'Hyperkalemia', whyNot: 'Hyperkalemia tents the T waves and widens the QRS; here it is the ST segment that is elevated.' },
      { id: 'd', text: 'Benign early repolarization', whyNot: 'Early repolarization is a stable, concave elevation without symptoms; ischemic elevation coves in a symptomatic patient.' },
    ],
    discriminator: 'Convex ST elevation in a coronary territory with ischemic symptoms is a STEMI regardless of heart rate — the elevation, not the rate, is the emergency.',
    tags: { system: 'cardiovascular', complaint: 'chest pain', rotation: ['em', 'im'], level: 'both' },
    difficultySeed: 0.7, source: [{ ref: 'ACC/AHA Chest Pain Guideline', year: 2021 }],
  },
  {
    itemId: 'ecg-vt-alt1', version: 1, type: 'ecg', conceptId: 'ecg-vt',
    stem: 'A patient with prior cardiomyopathy and an ICD, feeling palpitations. Read the strip.',
    vitals: [], findings: [],
    ecg: { rate: 160, regularity: 'regular', pWave: 'absent', qrsWide: true, tWave: 'inverted', lead: 'Lead II' },
    options: [
      { id: 'a', text: 'Ventricular tachycardia', correct: true },
      { id: 'b', text: 'Atrial flutter with aberrancy', whyNot: 'Flutter shows sawtooth atrial waves; a broad, regular, P-less run in a cardiomyopath is VT.' },
      { id: 'c', text: 'Sinus tachycardia', whyNot: 'Sinus tachycardia is narrow with P waves; this is wide and P-less.' },
      { id: 'd', text: 'AVNRT', whyNot: 'AVNRT is narrow-complex; the broad QRS here places the origin in the ventricle.' },
    ],
    discriminator: 'A regular wide-complex tachycardia without P waves in a patient with structural heart disease is ventricular tachycardia until proven otherwise.',
    tags: { system: 'cardiovascular', complaint: 'palpitations', rotation: ['em', 'im'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'AHA/ACC/HRS Ventricular Arrhythmias Guideline', year: 2017 }],
  },

  /* ══════════ BUZZWORDS — pool depth ══════════ */
  {
    itemId: 'assoc-heinz-g6pd-1', version: 1, type: 'association', conceptId: 'assoc-heinz-g6pd',
    stem: 'Heinz bodies and bite cells on the smear with acute hemolysis after an antibiotic (or fava beans) in a young man.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'G6PD deficiency', correct: true },
      { id: 'b', text: 'Hereditary spherocytosis', whyNot: 'Spherocytosis shows spherocytes with a positive osmotic fragility, not Heinz bodies and bite cells after an oxidant.' },
      { id: 'c', text: 'Autoimmune hemolytic anemia', whyNot: 'AIHA is Coombs-positive with spherocytes, not oxidant-triggered Heinz-body hemolysis.' },
      { id: 'd', text: 'Sickle cell anemia', whyNot: 'Sickle disease shows sickled cells and a positive sickle solubility test, not bite cells after an oxidant drug.' },
    ],
    discriminator: 'Oxidant-induced hemolysis with Heinz bodies and bite cells is G6PD deficiency — the enzyme cannot protect red cells from oxidative stress, so they are pitted by the spleen.',
    tags: { system: 'heme_onc', complaint: 'buzzword', rotation: ['im'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'WHO Working Group: G6PD Deficiency', year: 2022 }],
  },
  {
    itemId: 'assoc-howell-jolly-1', version: 1, type: 'association', conceptId: 'assoc-howell-jolly',
    stem: 'Howell–Jolly bodies (nuclear remnants) in red cells on a routine smear.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Asplenia / functional hyposplenism', correct: true },
      { id: 'b', text: 'Iron deficiency anemia', whyNot: 'Iron deficiency shows microcytic hypochromic cells, not retained nuclear remnants — those signal a spleen not clearing them.' },
      { id: 'c', text: 'B12 deficiency', whyNot: 'B12 deficiency gives macro-ovalocytes and hypersegmented neutrophils, not Howell–Jolly bodies from an absent spleen.' },
      { id: 'd', text: 'Thalassemia', whyNot: 'Thalassemia shows target cells and microcytosis; Howell–Jolly bodies specifically indicate splenic dysfunction.' },
    ],
    discriminator: 'Howell–Jolly bodies mean the spleen is not pitting nuclear remnants — a marker of asplenia or functional hyposplenism (e.g., sickle cell autosplenectomy).',
    tags: { system: 'heme_onc', complaint: 'buzzword', rotation: ['im'], level: 'both', boards: ['step1'] },
    difficultySeed: 0.5, source: [{ ref: 'BCSH Guideline: Prevention of Infection in Asplenia', year: 2011 }],
  },
  {
    itemId: 'assoc-basophilic-stippling-1', version: 1, type: 'association', conceptId: 'assoc-basophilic-stippling',
    stem: 'Basophilic stippling of red cells with a microcytic anemia, abdominal pain and a peripheral neuropathy in an adult with old-house renovation exposure.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Lead poisoning', correct: true },
      { id: 'b', text: 'Iron deficiency', whyNot: 'Iron deficiency is microcytic but lacks basophilic stippling, neuropathy and the lead exposure history.' },
      { id: 'c', text: 'Sideroblastic anemia (alcohol)', whyNot: 'Sideroblastic anemia shows ringed sideroblasts on marrow; the stippling plus exposure and neuropathy point to lead.' },
      { id: 'd', text: 'Thalassemia', whyNot: 'Thalassemia gives target cells and a family history, not stippling with a toxic exposure and neuropathy.' },
    ],
    discriminator: 'Basophilic stippling with microcytic anemia, neuropathy and abdominal pain after lead exposure is plumbism — lead inhibits heme synthesis and RNA breakdown.',
    tags: { system: 'heme_onc', complaint: 'buzzword', rotation: ['im', 'peds'], level: 'both', boards: ['step1'] },
    difficultySeed: 0.5, source: [{ ref: 'CDC Guidelines on Lead Exposure', year: 2021 }],
  },
  {
    itemId: 'assoc-anti-ttg-1', version: 1, type: 'association', conceptId: 'assoc-anti-ttg',
    stem: 'Anti-tissue-transglutaminase (anti-tTG) antibodies with chronic diarrhea, weight loss, iron-deficiency anemia and an intensely itchy vesicular rash on the elbows.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Celiac disease', correct: true },
      { id: 'b', text: 'Crohn disease', whyNot: 'Crohn is not defined by anti-tTG or dermatitis herpetiformis; those point specifically to celiac.' },
      { id: 'c', text: 'Irritable bowel syndrome', whyNot: 'IBS has no autoantibodies, malabsorption or rash.' },
      { id: 'd', text: 'Tropical sprue', whyNot: 'Tropical sprue follows travel and responds to antibiotics; it lacks anti-tTG and dermatitis herpetiformis.' },
    ],
    discriminator: 'Anti-tTG antibodies with malabsorption and the itchy vesicular rash of dermatitis herpetiformis is celiac disease — a gluten-driven villous atrophy.',
    tags: { system: 'gi', complaint: 'buzzword', rotation: ['im', 'fm'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'ACG Clinical Guideline: Celiac Disease', year: 2023 }],
  },
  {
    itemId: 'assoc-anti-centromere-1', version: 1, type: 'association', conceptId: 'assoc-anti-centromere',
    stem: 'Anti-centromere antibodies with Calcinosis, Raynaud, Esophageal dysmotility, Sclerodactyly and Telangiectasias.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Limited cutaneous systemic sclerosis (CREST)', correct: true },
      { id: 'b', text: 'Diffuse systemic sclerosis', whyNot: 'Diffuse disease carries anti-Scl-70 with rapid skin and early renal/lung involvement, not the anti-centromere CREST pattern.' },
      { id: 'c', text: 'Systemic lupus erythematosus', whyNot: 'Lupus is anti-dsDNA/Smith with a malar rash, not the CREST pentad with anti-centromere.' },
      { id: 'd', text: 'Mixed connective tissue disease', whyNot: 'MCTD is anti-U1-RNP with overlapping features, not the anti-centromere limited-scleroderma picture.' },
    ],
    discriminator: 'Anti-centromere antibodies with the CREST pentad is limited cutaneous systemic sclerosis — the antibody predicts the limited pattern and pulmonary hypertension risk.',
    tags: { system: 'msk_rheum', complaint: 'buzzword', rotation: ['im'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.5, source: [{ ref: 'ACR/EULAR Classification Criteria for Systemic Sclerosis', year: 2013 }],
  },
  {
    itemId: 'assoc-anti-scl70-1', version: 1, type: 'association', conceptId: 'assoc-anti-scl70',
    stem: 'Anti-Scl-70 (anti-topoisomerase I) antibodies with rapidly progressive diffuse skin thickening and early interstitial lung disease.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Diffuse cutaneous systemic sclerosis', correct: true },
      { id: 'b', text: 'Limited scleroderma (CREST)', whyNot: 'Limited disease is anti-centromere with slow, distal skin change — anti-Scl-70 marks the diffuse, organ-threatening form.' },
      { id: 'c', text: 'Dermatomyositis', whyNot: 'Dermatomyositis has a heliotrope rash and Gottron papules with anti-Jo-1, not diffuse sclerosis with anti-Scl-70.' },
      { id: 'd', text: 'Eosinophilic fasciitis', whyNot: 'Eosinophilic fasciitis spares the fingers and lacks anti-Scl-70 and Raynaud.' },
    ],
    discriminator: 'Anti-Scl-70 with rapid, proximal skin thickening and interstitial lung disease is diffuse systemic sclerosis — the antibody flags the aggressive phenotype and scleroderma renal crisis risk.',
    tags: { system: 'msk_rheum', complaint: 'buzzword', rotation: ['im'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.5, source: [{ ref: 'ACR/EULAR Classification Criteria for Systemic Sclerosis', year: 2013 }],
  },
  {
    itemId: 'assoc-anti-ro-la-1', version: 1, type: 'association', conceptId: 'assoc-anti-ro-la',
    stem: 'Anti-Ro (SSA) and anti-La (SSB) antibodies with dry eyes, dry mouth and bilateral parotid enlargement.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Sjögren syndrome', correct: true },
      { id: 'b', text: 'Systemic lupus erythematosus', whyNot: 'Lupus centres on anti-dsDNA/Smith; anti-Ro/La with sicca and parotid swelling is Sjögren (though the antibodies can overlap).' },
      { id: 'c', text: 'Sarcoidosis', whyNot: 'Sarcoid parotid involvement lacks anti-Ro/La and the autoimmune sicca antibody profile.' },
      { id: 'd', text: 'IgG4-related disease', whyNot: 'IgG4 disease causes glandular swelling with high IgG4, not anti-Ro/La with sicca symptoms.' },
    ],
    discriminator: 'Anti-Ro/La with the sicca complex and parotid enlargement is Sjögren syndrome — the antibodies also carry a neonatal-lupus and congenital heart block risk in pregnancy.',
    tags: { system: 'msk_rheum', complaint: 'buzzword', rotation: ['im'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'ACR/EULAR Classification Criteria for Sjögren', year: 2016 }],
  },
  {
    itemId: 'assoc-negri-1', version: 1, type: 'association', conceptId: 'assoc-negri',
    stem: 'Negri bodies (eosinophilic cytoplasmic inclusions) in neurons, with hydrophobia, agitation and hypersalivation weeks after a bat exposure.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Rabies', correct: true },
      { id: 'b', text: 'Herpes simplex encephalitis', whyNot: 'HSV encephalitis gives temporal-lobe changes and Cowdry inclusions, not Negri bodies and hydrophobia after an animal bite.' },
      { id: 'c', text: 'Tetanus', whyNot: 'Tetanus causes trismus and muscle spasms without Negri bodies or hydrophobia.' },
      { id: 'd', text: 'Bacterial meningitis', whyNot: 'Meningitis is an acute neutrophilic CSF process, not a Negri-body encephalitis with hydrophobia.' },
    ],
    discriminator: 'Negri bodies with hydrophobia and hypersalivation after a bat or dog exposure is rabies — a near-uniformly fatal encephalitis once symptomatic, so post-exposure prophylaxis is everything.',
    tags: { system: 'infectious', complaint: 'buzzword', rotation: ['im', 'em'], level: 'both', boards: ['step1'] },
    difficultySeed: 0.5, source: [{ ref: 'WHO Expert Consultation on Rabies', year: 2018 }],
  },
  {
    itemId: 'assoc-koplik-1', version: 1, type: 'association', conceptId: 'assoc-koplik',
    stem: 'Koplik spots (tiny white papules on an erythematous buccal mucosa) with high fever, cough, coryza and conjunctivitis before a descending maculopapular rash.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Measles', correct: true },
      { id: 'b', text: 'Rubella', whyNot: 'Rubella has posterior auricular lymphadenopathy and a milder course without Koplik spots or the three Cs.' },
      { id: 'c', text: 'Scarlet fever', whyNot: 'Scarlet fever gives a sandpaper rash and strawberry tongue, not Koplik spots with coryza and conjunctivitis.' },
      { id: 'd', text: 'Kawasaki disease', whyNot: 'Kawasaki lacks Koplik spots and coryza; it is a vasculitis with prolonged fever and mucocutaneous changes.' },
    ],
    discriminator: 'Koplik spots with cough, coryza and conjunctivitis before a cephalocaudal rash are pathognomonic for measles — the enanthem precedes the exanthem.',
    tags: { system: 'infectious', complaint: 'buzzword', rotation: ['peds', 'fm'], level: 'both', boards: ['step1'] },
    difficultySeed: 0.55, source: [{ ref: 'CDC Manual for Surveillance of Vaccine-Preventable Diseases', year: 2021 }],
  },
  {
    itemId: 'assoc-slapped-cheek-1', version: 1, type: 'association', conceptId: 'assoc-slapped-cheek',
    stem: 'A child with bright red "slapped cheeks" followed by a lacy reticular rash on the arms, with mild fever.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Erythema infectiosum (parvovirus B19)', correct: true },
      { id: 'b', text: 'Measles', whyNot: 'Measles has Koplik spots and the three Cs with a descending rash, not slapped cheeks and a lacy pattern.' },
      { id: 'c', text: 'Roseola', whyNot: 'Roseola is high fever that breaks before a truncal rash appears, without slapped cheeks.' },
      { id: 'd', text: 'Scarlet fever', whyNot: 'Scarlet fever is a sandpaper rash with strawberry tongue after strep pharyngitis, not a facial slapped-cheek rash.' },
    ],
    discriminator: 'Slapped-cheek facial erythema then a lacy reticular rash is parvovirus B19 (fifth disease) — beware aplastic crisis in sickle cell and hydrops in pregnancy.',
    tags: { system: 'infectious', complaint: 'buzzword', rotation: ['peds', 'fm'], level: 'both', boards: ['step1'] },
    difficultySeed: 0.55, source: [{ ref: 'AAP Red Book', year: 2021 }],
  },
  {
    itemId: 'assoc-strawberry-tongue-1', version: 1, type: 'association', conceptId: 'assoc-strawberry-tongue',
    stem: 'A child with five days of high fever, bilateral non-exudative conjunctivitis, a strawberry tongue with cracked lips, a polymorphous rash, and swollen red hands now peeling.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Kawasaki disease', correct: true },
      { id: 'b', text: 'Scarlet fever', whyNot: 'Scarlet fever shares the strawberry tongue but follows strep pharyngitis and responds to penicillin; the ≥5-day fever with conjunctivitis and extremity changes is Kawasaki.' },
      { id: 'c', text: 'Measles', whyNot: 'Measles has Koplik spots and coryza, not the extremity swelling/peeling and prolonged fever of Kawasaki.' },
      { id: 'd', text: 'Staphylococcal scalded skin', whyNot: 'SSSS causes skin sloughing with a positive Nikolsky sign, not the mucocutaneous vasculitic picture of Kawasaki.' },
    ],
    discriminator: 'Five days of fever with conjunctivitis, mucositis, rash, extremity changes and adenopathy is Kawasaki disease — treat with IVIG and aspirin to prevent coronary aneurysms.',
    tags: { system: 'cardiovascular', complaint: 'buzzword', rotation: ['peds'], level: 'both', boards: ['step2'] },
    difficultySeed: 0.55, source: [{ ref: 'AHA Guideline for Diagnosis & Management of Kawasaki Disease', year: 2017 }],
  },
  {
    itemId: 'assoc-currant-jelly-stool-1', version: 1, type: 'association', conceptId: 'assoc-currant-jelly-stool',
    stem: 'An infant with episodic inconsolable crying and drawing up the legs, a sausage-shaped right abdominal mass, and currant-jelly stools.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Intussusception', correct: true },
      { id: 'b', text: 'Pyloric stenosis', whyNot: 'Pyloric stenosis gives non-bilious projectile vomiting and an olive mass, not colicky pain with currant-jelly stools.' },
      { id: 'c', text: 'Malrotation with volvulus', whyNot: 'Volvulus causes bilious vomiting and a surgical abdomen; the sausage mass and currant-jelly stool are intussusception.' },
      { id: 'd', text: 'Meckel diverticulum', whyNot: 'Meckel causes painless rectal bleeding, not colicky pain with a telescoping bowel mass.' },
    ],
    discriminator: 'Colicky pain, a sausage-shaped mass and currant-jelly stools in an infant is intussusception — an air or contrast enema is both diagnostic and often therapeutic.',
    tags: { system: 'gi', complaint: 'buzzword', rotation: ['peds', 'surg'], level: 'both', boards: ['step2'] },
    difficultySeed: 0.55, source: [{ ref: 'Nelson Textbook of Pediatrics', year: 2020 }],
  },
  {
    itemId: 'assoc-olive-mass-1', version: 1, type: 'association', conceptId: 'assoc-olive-mass',
    stem: 'A 4-week-old with progressive non-bilious projectile vomiting after feeds, a palpable olive-shaped epigastric mass, and a hypochloremic hypokalemic metabolic alkalosis.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Pyloric stenosis', correct: true },
      { id: 'b', text: 'Gastroesophageal reflux', whyNot: 'Reflux is effortless spit-up without an olive mass or a hypochloremic alkalosis.' },
      { id: 'c', text: 'Duodenal atresia', whyNot: 'Duodenal atresia presents at birth with bilious vomiting and a double-bubble sign, not a 4-week olive mass.' },
      { id: 'd', text: 'Intussusception', whyNot: 'Intussusception gives colicky pain and currant-jelly stools, not projectile vomiting with an olive mass.' },
    ],
    discriminator: 'Projectile non-bilious vomiting with an olive mass and a hypochloremic hypokalemic alkalosis at 3–6 weeks is pyloric stenosis — correct the electrolytes before the pyloromyotomy.',
    tags: { system: 'gi', complaint: 'buzzword', rotation: ['peds', 'surg'], level: 'both', boards: ['step2'] },
    difficultySeed: 0.55, source: [{ ref: 'Nelson Textbook of Pediatrics', year: 2020 }],
  },
  {
    itemId: 'assoc-boot-shaped-heart-1', version: 1, type: 'association', conceptId: 'assoc-boot-shaped-heart',
    stem: 'A cyanotic infant with "tet spells" relieved by squatting, a harsh systolic murmur, and a boot-shaped heart on chest X-ray.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Tetralogy of Fallot', correct: true },
      { id: 'b', text: 'Transposition of the great arteries', whyNot: 'Transposition shows an "egg-on-a-string" heart and presents with early cyanosis, not a boot shape with tet spells relieved by squatting.' },
      { id: 'c', text: 'Ventricular septal defect', whyNot: 'An isolated VSD is acyanotic with a holosystolic murmur, not cyanotic spells and a boot-shaped heart.' },
      { id: 'd', text: 'Coarctation of the aorta', whyNot: 'Coarctation gives rib notching and differential blood pressures, not cyanotic squatting spells.' },
    ],
    discriminator: 'Cyanotic spells relieved by squatting with a boot-shaped heart is Tetralogy of Fallot — squatting raises systemic resistance and reduces the right-to-left shunt.',
    tags: { system: 'cardiovascular', complaint: 'buzzword', rotation: ['peds'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'AHA/ACC Adult Congenital Heart Disease Guideline', year: 2018 }],
  },
  {
    itemId: 'assoc-cherry-red-macula-1', version: 1, type: 'association', conceptId: 'assoc-cherry-red-macula',
    stem: 'A Jewish infant with progressive weakness, loss of motor milestones, an exaggerated startle response, and a cherry-red spot on the macula — with no hepatosplenomegaly.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Tay–Sachs disease', correct: true },
      { id: 'b', text: 'Niemann–Pick disease', whyNot: 'Niemann–Pick also shows a cherry-red spot but has prominent hepatosplenomegaly, which Tay–Sachs lacks.' },
      { id: 'c', text: 'Gaucher disease', whyNot: 'Gaucher has hepatosplenomegaly and crumpled-paper macrophages without a cherry-red macula.' },
      { id: 'd', text: 'Krabbe disease', whyNot: 'Krabbe causes a demyelinating leukodystrophy with globoid cells, not a cherry-red macula.' },
    ],
    discriminator: 'A cherry-red macula with neurodegeneration and an exaggerated startle but NO organomegaly is Tay–Sachs (hexosaminidase A deficiency) — the absent hepatosplenomegaly separates it from Niemann–Pick.',
    tags: { system: 'neuro', complaint: 'buzzword', rotation: ['peds'], level: 'both', boards: ['step1'] },
    difficultySeed: 0.5, source: [{ ref: 'GeneReviews: Hexosaminidase A Deficiency', year: 2020 }],
  },
  {
    itemId: 'assoc-erythema-migrans-1', version: 1, type: 'association', conceptId: 'assoc-erythema-migrans',
    stem: 'An expanding target-shaped (bull\'s-eye) rash with central clearing, fever and arthralgia after a hike in the northeastern United States.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Lyme disease', correct: true },
      { id: 'b', text: 'Erythema multiforme', whyNot: 'Erythema multiforme gives fixed target lesions on the palms/soles from drugs or HSV, not a single expanding migrating ring after a tick exposure.' },
      { id: 'c', text: 'Cellulitis', whyNot: 'Cellulitis is a uniformly red, warm, tender plaque without central clearing or a target morphology.' },
      { id: 'd', text: 'Tinea corporis', whyNot: 'Ringworm is a scaly annular plaque that itches, not an expanding erythema migrans with systemic symptoms.' },
    ],
    discriminator: 'An expanding bull\'s-eye rash with central clearing after a tick exposure is erythema migrans of Lyme disease — treat with doxycycline before serology even turns positive.',
    tags: { system: 'infectious', complaint: 'buzzword', rotation: ['fm', 'im'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'IDSA/AAN/ACR Guideline for Lyme Disease', year: 2020 }],
  },
];

export const EXPANSION2: ContentModule = { concepts, subtopics, alsoSystems, items };
