/* ══════════════════════════════════════════════════════════════
   Content expansion #3 — filling the empty subtopics.

   One or more original, publicly-cited concepts for every empty
   taxonomy subtopic: Pediatrics, Psychiatry, Reproductive,
   Multisystem, Infectious, Dermatology, Heme/Onc, GI, Endocrine,
   Pulmonary and the HTN/lipids gap.

   Sourcing (see docs/CONTENT_POLICY.md): every vignette cites a
   PUBLIC clinical-evidence source — agency (CDC/WHO), specialty
   guideline, USPSTF, or peer-reviewed literature. Commercial
   board-prep products are coverage-only and are never copied or
   cited. All concepts UNREVIEWED; synthetic patients only.
   ══════════════════════════════════════════════════════════════ */

import { v, type ContentModule, type RawConcept, type RawItem } from './authoring';
import type { System } from '../types';

const concepts: RawConcept[] = [
  /* Cardiovascular — HTN & lipids */
  { conceptId: 'htn-emergency', name: 'Hypertensive emergency vs urgency', system: 'cardiovascular', topic: 'Hypertension' },
  { conceptId: 'secondary-htn', name: 'Secondary hypertension', system: 'cardiovascular', topic: 'Hypertension' },
  { conceptId: 'familial-hypercholesterolemia', name: 'Familial hypercholesterolemia', system: 'cardiovascular', topic: 'Dyslipidemia' },

  /* Pulmonary gaps */
  { conceptId: 'sarcoidosis', name: 'Sarcoidosis', system: 'pulmonary', topic: 'Interstitial lung disease' },
  { conceptId: 'ipf', name: 'Idiopathic pulmonary fibrosis', system: 'pulmonary', topic: 'Interstitial lung disease' },
  { conceptId: 'ards', name: 'Acute respiratory distress syndrome', system: 'pulmonary', topic: 'Respiratory failure' },
  { conceptId: 'lung-cancer-types', name: 'Lung cancer subtypes', system: 'pulmonary', topic: 'Lung neoplasm' },
  { conceptId: 'pulmonary-htn', name: 'Pulmonary hypertension', system: 'pulmonary', topic: 'Pulmonary vascular disease' },

  /* GI gaps */
  { conceptId: 'c-diff', name: 'Clostridioides difficile colitis', system: 'gi', topic: 'Infectious colitis' },
  { conceptId: 'colorectal-cancer', name: 'Colorectal cancer', system: 'gi', topic: 'GI neoplasm' },
  { conceptId: 'pancreatic-cancer', name: 'Pancreatic cancer', system: 'gi', topic: 'GI neoplasm' },

  /* Endocrine gaps */
  { conceptId: 'metabolic-syndrome', name: 'Metabolic syndrome', system: 'endocrine', topic: 'Metabolic disorders' },
  { conceptId: 'cah', name: 'Congenital adrenal hyperplasia', system: 'endocrine', topic: 'Reproductive endocrinology' },
  { conceptId: 'hypoglycemia', name: 'Hypoglycemia (Whipple triad)', system: 'endocrine', topic: 'Diabetic emergencies' },

  /* Heme / Onc gaps */
  { conceptId: 'coagulopathy-labs', name: 'Bleeding disorders by PT/PTT', system: 'heme_onc', topic: 'Bleeding disorders' },
  { conceptId: 'dic', name: 'Disseminated intravascular coagulation', system: 'heme_onc', topic: 'Bleeding disorders' },
  { conceptId: 'cord-compression', name: 'Malignant spinal cord compression', system: 'heme_onc', topic: 'Oncologic emergencies' },
  { conceptId: 'tumor-lysis', name: 'Tumor lysis syndrome', system: 'heme_onc', topic: 'Oncologic emergencies' },
  { conceptId: 'febrile-neutropenia', name: 'Febrile neutropenia', system: 'heme_onc', topic: 'Oncologic emergencies' },
  { conceptId: 'transfusion-reactions', name: 'Transfusion reactions', system: 'heme_onc', topic: 'Transfusion medicine' },

  /* Infectious gaps */
  { conceptId: 'sepsis-recognition', name: 'Sepsis recognition', system: 'infectious', topic: 'Sepsis' },
  { conceptId: 'sepsis-bundle', name: 'Sepsis first-hour bundle', system: 'infectious', topic: 'Sepsis' },
  { conceptId: 'infectious-diarrhea', name: 'Infectious diarrhea', system: 'infectious', topic: 'GI infection' },
  { conceptId: 'asymptomatic-bacteriuria', name: 'When to treat bacteriuria', system: 'infectious', topic: 'Urinary infection' },
  { conceptId: 'hsv-encephalitis', name: 'HSV encephalitis', system: 'infectious', topic: 'CNS infection' },
  { conceptId: 'cellulitis-vs-erysipelas', name: 'Cellulitis vs erysipelas vs abscess', system: 'infectious', topic: 'Skin & soft tissue infection' },

  /* Dermatology gaps */
  { conceptId: 'psoriasis', name: 'Psoriasis', system: 'dermatology', topic: 'Papulosquamous disease' },
  { conceptId: 'atopic-dermatitis', name: 'Atopic dermatitis', system: 'dermatology', topic: 'Eczematous disease' },
  { conceptId: 'erythema-nodosum', name: 'Erythema nodosum', system: 'dermatology', topic: 'Cutaneous signs of systemic disease' },
  { conceptId: 'acanthosis-nigricans', name: 'Acanthosis nigricans', system: 'dermatology', topic: 'Cutaneous signs of systemic disease' },
  { conceptId: 'ace-angioedema', name: 'ACE-inhibitor angioedema', system: 'dermatology', topic: 'Urticaria & hypersensitivity' },
  { conceptId: 'erythema-multiforme', name: 'Erythema multiforme', system: 'dermatology', topic: 'Urticaria & hypersensitivity' },

  /* Psychiatry gaps */
  { conceptId: 'psychosis-timeline', name: 'Psychotic disorders by duration', system: 'psychiatry', topic: 'Psychotic disorders' },
  { conceptId: 'anxiety-differential', name: 'Anxiety disorders differential', system: 'psychiatry', topic: 'Anxiety disorders' },
  { conceptId: 'dementia-types', name: 'Dementia subtypes', system: 'psychiatry', topic: 'Neurocognitive disorders' },
  { conceptId: 'somatic-spectrum', name: 'Somatic symptom & related disorders', system: 'psychiatry', topic: 'Somatic & factitious' },
  { conceptId: 'adhd', name: 'ADHD', system: 'psychiatry', topic: 'Neurodevelopmental disorders' },
  { conceptId: 'autism', name: 'Autism spectrum disorder', system: 'psychiatry', topic: 'Neurodevelopmental disorders' },
  { conceptId: 'anorexia-vs-bulimia', name: 'Anorexia vs bulimia nervosa', system: 'psychiatry', topic: 'Eating disorders' },

  /* Reproductive gaps */
  { conceptId: 'postmenopausal-bleeding', name: 'Postmenopausal bleeding', system: 'reproductive', topic: 'Gynecologic oncology' },
  { conceptId: 'cervical-screening', name: 'Cervical cancer screening', system: 'reproductive', topic: 'Gynecologic oncology' },
  { conceptId: 'breast-mass', name: 'Breast mass evaluation', system: 'reproductive', topic: 'Breast disease' },
  { conceptId: 'pcos', name: 'Polycystic ovary syndrome', system: 'reproductive', topic: 'Infertility & menstrual' },
  { conceptId: 'amenorrhea-workup', name: 'Primary vs secondary amenorrhea', system: 'reproductive', topic: 'Infertility & menstrual' },
  { conceptId: 'vaginitis', name: 'Vaginitis (BV vs trich vs candida)', system: 'reproductive', topic: 'Genital infection' },
  { conceptId: 'syphilis-stages', name: 'Syphilis stages', system: 'reproductive', topic: 'Genital infection' },
  { conceptId: 'contraception-contraindication', name: 'Estrogen contraindications', system: 'reproductive', topic: 'Contraception' },

  /* Multisystem gaps */
  { conceptId: 'shock-types', name: 'Classifying shock', system: 'multisystem', topic: 'Shock' },
  { conceptId: 'hyponatremia-approach', name: 'Hyponatremia by volume status', system: 'multisystem', topic: 'Fluids & electrolytes' },
  { conceptId: 'vitamin-deficiency', name: 'Vitamin deficiency syndromes', system: 'multisystem', topic: 'Nutrition' },
  { conceptId: 'geriatric-falls', name: 'Falls & polypharmacy', system: 'multisystem', topic: 'Geriatrics' },
  { conceptId: 'cancer-screening', name: 'Adult cancer screening thresholds', system: 'multisystem', topic: 'Preventive medicine' },
  { conceptId: 'inheritance-patterns', name: 'Modes of inheritance', system: 'multisystem', topic: 'Genetics' },

  /* Pediatrics gaps */
  { conceptId: 'croup-vs-epiglottitis', name: 'Croup vs epiglottitis', system: 'pediatrics', topic: 'Pediatric airway' },
  { conceptId: 'bronchiolitis', name: 'Bronchiolitis', system: 'pediatrics', topic: 'Pediatric respiratory' },
  { conceptId: 'nrds-vs-ttn', name: 'RDS vs transient tachypnea', system: 'pediatrics', topic: 'Neonatology' },
  { conceptId: 'neonatal-jaundice', name: 'Neonatal jaundice', system: 'pediatrics', topic: 'Neonatology' },
  { conceptId: 'febrile-infant', name: 'The febrile young infant', system: 'pediatrics', topic: 'Pediatric infectious disease' },
  { conceptId: 'developmental-milestones', name: 'Developmental milestones', system: 'pediatrics', topic: 'Growth & development' },
  { conceptId: 'ductal-dependent-chd', name: 'Ductal-dependent cyanotic CHD', system: 'pediatrics', topic: 'Congenital & genetic' },
  { conceptId: 'hirschsprung', name: 'Hirschsprung disease', system: 'pediatrics', topic: 'Pediatric GI' },
  { conceptId: 'malrotation-volvulus', name: 'Malrotation with midgut volvulus', system: 'pediatrics', topic: 'Pediatric GI' },
  { conceptId: 'live-vaccine-contraindication', name: 'Live vaccine contraindications', system: 'pediatrics', topic: 'Immunization' },
];

const subtopics: Record<string, string> = {
  'htn-emergency': 'cv.htn-lipids', 'secondary-htn': 'cv.htn-lipids', 'familial-hypercholesterolemia': 'cv.htn-lipids',
  'sarcoidosis': 'pulm.parenchyma', 'ipf': 'pulm.parenchyma', 'ards': 'pulm.critical',
  'lung-cancer-types': 'pulm.neoplasm', 'pulmonary-htn': 'pulm.vascular',
  'c-diff': 'gi.infectious', 'colorectal-cancer': 'gi.neoplasm', 'pancreatic-cancer': 'gi.neoplasm',
  'metabolic-syndrome': 'endo.lipid-metab', 'cah': 'endo.repro-endo', 'hypoglycemia': 'endo.diabetes',
  'coagulopathy-labs': 'heme.hemostasis', 'dic': 'heme.hemostasis',
  'cord-compression': 'onc.solid', 'tumor-lysis': 'onc.solid', 'febrile-neutropenia': 'onc.solid',
  'transfusion-reactions': 'heme.transfusion',
  'sepsis-recognition': 'id.sepsis', 'sepsis-bundle': 'id.sepsis', 'infectious-diarrhea': 'id.gi-id',
  'asymptomatic-bacteriuria': 'id.uti-id', 'hsv-encephalitis': 'id.cns-id', 'cellulitis-vs-erysipelas': 'id.skin-soft',
  'psoriasis': 'derm.inflammatory', 'atopic-dermatitis': 'derm.inflammatory',
  'erythema-nodosum': 'derm.systemic', 'acanthosis-nigricans': 'derm.systemic',
  'ace-angioedema': 'derm.hypersensitivity', 'erythema-multiforme': 'derm.hypersensitivity',
  'psychosis-timeline': 'psych.psychotic', 'anxiety-differential': 'psych.anxiety',
  'dementia-types': 'psych.neurocognitive', 'somatic-spectrum': 'psych.somatic-personality',
  'adhd': 'psych.child-psych', 'autism': 'psych.child-psych', 'anorexia-vs-bulimia': 'psych.eating',
  'postmenopausal-bleeding': 'repro.gyn-onc', 'cervical-screening': 'repro.gyn-onc',
  'breast-mass': 'repro.breast', 'pcos': 'repro.infertility', 'amenorrhea-workup': 'repro.infertility',
  'vaginitis': 'repro.sti', 'syphilis-stages': 'repro.sti', 'contraception-contraindication': 'repro.contraception',
  'shock-types': 'multi.shock', 'hyponatremia-approach': 'multi.acid-base-fluids',
  'vitamin-deficiency': 'multi.nutrition-vitamin', 'geriatric-falls': 'multi.geriatrics',
  'cancer-screening': 'multi.preventive', 'inheritance-patterns': 'multi.genetics',
  'croup-vs-epiglottitis': 'peds.peds-respiratory', 'bronchiolitis': 'peds.peds-respiratory',
  'nrds-vs-ttn': 'peds.neonatal', 'neonatal-jaundice': 'peds.neonatal',
  'febrile-infant': 'peds.peds-infectious', 'developmental-milestones': 'peds.development',
  'ductal-dependent-chd': 'peds.congenital-genetic', 'hirschsprung': 'peds.peds-gi',
  'malrotation-volvulus': 'peds.peds-gi', 'live-vaccine-contraindication': 'peds.vaccines',
};

const alsoSystems: Record<string, System[]> = {
  'metabolic-syndrome': ['cardiovascular'],
  'cord-compression': ['neuro'],
  'infectious-diarrhea': ['gi'],
  'hsv-encephalitis': ['neuro'],
  'cellulitis-vs-erysipelas': ['dermatology'],
  'pulmonary-htn': ['cardiovascular'],
  'ace-angioedema': ['multisystem'],
  'malrotation-volvulus': ['gi'],
};

const items: RawItem[] = [
  /* ── Cardiovascular: HTN & lipids ── */
  {
    itemId: 'htn-emergency-1', version: 1, type: 'discriminator', conceptId: 'htn-emergency',
    stem: 'A patient has a blood pressure of 220/125. What single element decides "hypertensive emergency" (needing IV therapy) rather than "urgency"?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Evidence of acute end-organ damage', correct: true },
      { id: 'b', text: 'The absolute systolic number', whyNot: 'Severity is defined by target-organ injury, not by a pressure threshold alone.' },
      { id: 'c', text: 'A headache', whyNot: 'Headache is nonspecific; it is not the same as encephalopathy, ischemia or acute kidney injury.' },
      { id: 'd', text: 'The patient feeling anxious', whyNot: 'Symptoms of anxiety do not define an emergency; acute organ damage does.' },
    ],
    discriminator: 'A hypertensive emergency is severe hypertension WITH acute end-organ damage (encephalopathy, ACS, dissection, pulmonary edema, AKI, eclampsia) — without it, it is urgency treated with oral agents.',
    teachingPoint: 'In a true emergency lower the pressure in a controlled way (often ~25% in the first hour), not abruptly.',
    tags: { system: 'cardiovascular', complaint: 'hypertension', rotation: ['em', 'im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'ACC/AHA Guideline for High Blood Pressure in Adults', year: 2017 }],
  },
  {
    itemId: 'secondary-htn-1', version: 1, type: 'one_liner', conceptId: 'secondary-htn',
    stem: '32 F with resistant hypertension on three drugs, episodes of muscle weakness, and unprovoked hypokalemia.',
    vitals: [v('BP', '168/104', true), v('K', '2.9', true)],
    findings: ['Elevated aldosterone-to-renin ratio.'],
    options: [
      { id: 'a', text: 'Primary hyperaldosteronism', correct: true },
      { id: 'b', text: 'Essential hypertension', whyNot: 'Essential hypertension does not cause spontaneous hypokalemia with a high aldosterone-to-renin ratio in a young resistant patient.' },
      { id: 'c', text: 'Pheochromocytoma', whyNot: 'Pheo gives paroxysmal hypertension with headache/sweating/palpitations and raised metanephrines, not hypokalemia with high aldosterone.' },
      { id: 'd', text: 'Renal artery stenosis', whyNot: 'Renovascular disease raises renin; here renin is suppressed with high aldosterone, pointing to a primary adrenal source.' },
    ],
    discriminator: 'Resistant hypertension with spontaneous hypokalemia and a high aldosterone-to-renin ratio is primary hyperaldosteronism — young or resistant hypertension warrants a secondary-cause screen.',
    tags: { system: 'cardiovascular', complaint: 'hypertension', rotation: ['im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'Endocrine Society Guideline on Primary Aldosteronism', year: 2016 }],
  },
  {
    itemId: 'fh-1', version: 1, type: 'association', conceptId: 'familial-hypercholesterolemia',
    stem: 'Tendon xanthomas (Achilles, knuckles), a corneal arcus at a young age, very high LDL, and premature coronary disease running in the family.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Familial hypercholesterolemia', correct: true },
      { id: 'b', text: 'Familial hypertriglyceridemia', whyNot: 'High triglycerides cause eruptive xanthomas and pancreatitis, not tendon xanthomas with sky-high LDL.' },
      { id: 'c', text: 'Metabolic syndrome', whyNot: 'Metabolic syndrome is a cluster of central obesity, glucose and BP abnormalities, not monogenic LDL-receptor disease with tendon xanthomas.' },
      { id: 'd', text: 'Hypothyroidism', whyNot: 'Hypothyroid dyslipidemia is milder and reversible, without tendon xanthomas and early familial CAD.' },
    ],
    discriminator: 'Tendon xanthomas with very high LDL and premature familial coronary disease is familial hypercholesterolemia — an LDL-receptor defect needing early, intensive statin therapy.',
    tags: { system: 'cardiovascular', complaint: 'buzzword', rotation: ['im', 'fm'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'NHLBI/AHA/ACC Blood Cholesterol Guideline', year: 2018 }],
  },

  /* ── Pulmonary ── */
  {
    itemId: 'sarcoidosis-1', version: 1, type: 'association', conceptId: 'sarcoidosis',
    stem: 'A young Black woman with bilateral hilar lymphadenopathy on chest X-ray, non-caseating granulomas on biopsy, hypercalcemia and a high ACE level.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Sarcoidosis', correct: true },
      { id: 'b', text: 'Tuberculosis', whyNot: 'TB granulomas are caseating with organisms on stain; sarcoid granulomas are non-caseating and sterile.' },
      { id: 'c', text: 'Lymphoma', whyNot: 'Lymphoma causes adenopathy but not non-caseating granulomas with hypercalcemia and a raised ACE.' },
      { id: 'd', text: 'Hypersensitivity pneumonitis', whyNot: 'HP follows antigen exposure with poorly formed granulomas, not the bilateral hilar adenopathy and hypercalcemia of sarcoid.' },
    ],
    discriminator: 'Bilateral hilar adenopathy with non-caseating granulomas and hypercalcemia is sarcoidosis — granuloma macrophages activate vitamin D, driving the calcium up.',
    tags: { system: 'pulmonary', complaint: 'buzzword', rotation: ['im'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.6, source: [{ ref: 'ATS/ERS/WASOG Statement on Sarcoidosis', year: 2020 }],
  },
  {
    itemId: 'ipf-1', version: 1, type: 'one_liner', conceptId: 'ipf',
    stem: '68 M ex-smoker with a year of progressive exertional dyspnea and a dry cough, with fine "Velcro" crackles at the bases and clubbing.',
    vitals: [v('SpO₂', '92% RA', true)],
    findings: ['High-resolution CT: subpleural reticulation and honeycombing with a basal predominance.'],
    options: [
      { id: 'a', text: 'Idiopathic pulmonary fibrosis', correct: true },
      { id: 'b', text: 'Chronic heart failure', whyNot: 'Heart failure gives a raised JVP, S3 and a high BNP; IPF has clubbing and a honeycombed fibrotic CT.' },
      { id: 'c', text: 'COPD', whyNot: 'COPD is obstructive with hyperinflation, not the restrictive, honeycombed fibrosis of IPF.' },
      { id: 'd', text: 'Sarcoidosis', whyNot: 'Sarcoid shows hilar adenopathy and upper-zone disease, not basal honeycombing with clubbing.' },
    ],
    discriminator: 'Progressive dry cough with basal Velcro crackles, clubbing and subpleural honeycombing on CT is idiopathic pulmonary fibrosis — a usual-interstitial-pneumonia pattern.',
    tags: { system: 'pulmonary', complaint: 'dyspnea', rotation: ['im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'ATS/ERS/JRS/ALAT Guideline on IPF', year: 2022 }],
  },
  {
    itemId: 'ards-1', version: 1, type: 'one_liner', conceptId: 'ards',
    stem: 'A patient with severe pancreatitis develops rapid hypoxemic respiratory failure over a day, with diffuse bilateral infiltrates and a PaO₂/FiO₂ ratio of 150 — with no evidence of heart failure or fluid overload.',
    vitals: [v('SpO₂', '86% on high-flow', true), v('RR', '32', true)],
    findings: ['Echo: normal LV function; no elevated filling pressures.'],
    options: [
      { id: 'a', text: 'Acute respiratory distress syndrome', correct: true },
      { id: 'b', text: 'Cardiogenic pulmonary edema', whyNot: 'Cardiogenic edema has elevated filling pressures and cardiomegaly; ARDS infiltrates are non-cardiogenic with normal LV function.' },
      { id: 'c', text: 'Pneumonia in one lobe', whyNot: 'Lobar pneumonia is focal; ARDS is diffuse bilateral injury from a systemic insult.' },
      { id: 'd', text: 'Pulmonary embolism', whyNot: 'PE gives a clear chest with sudden hypoxemia, not diffuse bilateral infiltrates from capillary leak.' },
    ],
    discriminator: 'Acute bilateral infiltrates with severe hypoxemia (P/F ≤ 300) not explained by cardiac failure, within a week of an insult, is ARDS by the Berlin definition — treat with low-tidal-volume ventilation.',
    tags: { system: 'pulmonary', complaint: 'respiratory failure', rotation: ['im', 'em'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'Berlin Definition of ARDS (JAMA)', year: 2012 }],
  },
  {
    itemId: 'lung-cancer-1', version: 1, type: 'discriminator', conceptId: 'lung-cancer-types',
    stem: 'A central lung tumor in a heavy smoker causes hyponatremia (SIADH) and, in another patient, Cushing syndrome from ectopic ACTH. Which cancer is this?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Small cell lung cancer', correct: true },
      { id: 'b', text: 'Squamous cell carcinoma', whyNot: 'Squamous cell (also central) classically causes hypercalcemia via PTHrP, not SIADH or ectopic ACTH.' },
      { id: 'c', text: 'Adenocarcinoma', whyNot: 'Adenocarcinoma is peripheral and the commonest in non-smokers; the central, neuroendocrine paraneoplastic picture is small cell.' },
      { id: 'd', text: 'Bronchial carcinoid', whyNot: 'Carcinoid causes flushing/diarrhea from serotonin, not SIADH or ectopic ACTH from a smoking-related central tumour.' },
    ],
    discriminator: 'A central smoking-related tumour with SIADH or ectopic ACTH is small cell lung cancer; squamous cell (also central) instead raises calcium via PTHrP — the paraneoplastic syndrome names the histology.',
    tags: { system: 'pulmonary', complaint: 'buzzword', rotation: ['im'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'WHO Classification of Thoracic Tumours', year: 2021 }],
  },
  {
    itemId: 'pulmonary-htn-1', version: 1, type: 'one_liner', conceptId: 'pulmonary-htn',
    stem: '54 F with progressive exertional dyspnea and fatigue, now with a loud P2, a right ventricular heave and pedal edema; her lungs are clear.',
    vitals: [v('SpO₂', '93% RA', true)],
    findings: ['Echo: elevated estimated pulmonary artery pressure and a dilated right ventricle; right heart catheter mean PAP 30 mmHg.'],
    options: [
      { id: 'a', text: 'Pulmonary hypertension', correct: true },
      { id: 'b', text: 'Left heart failure', whyNot: 'Left failure floods the lungs with crackles and a raised wedge pressure; here the lungs are clear and the right heart is the one failing.' },
      { id: 'c', text: 'COPD', whyNot: 'COPD gives airflow obstruction and hyperinflation; the isolated right-heart strain with clear lungs points to the pulmonary vasculature.' },
      { id: 'd', text: 'Anemia', whyNot: 'Anemia causes dyspnea without a loud P2, RV heave and a raised pulmonary artery pressure.' },
    ],
    discriminator: 'Exertional dyspnea with a loud P2, RV heave and right heart failure but clear lungs is pulmonary hypertension — a mean pulmonary artery pressure above 20 mmHg on catheterization confirms it.',
    tags: { system: 'pulmonary', complaint: 'dyspnea', rotation: ['im'], level: 'clerkship' },
    difficultySeed: 0.55, source: [{ ref: 'ESC/ERS Guidelines on Pulmonary Hypertension', year: 2022 }],
  },

  /* ── GI ── */
  {
    itemId: 'c-diff-1', version: 1, type: 'one_liner', conceptId: 'c-diff',
    stem: 'A hospitalized patient develops profuse watery diarrhea, crampy abdominal pain and a rising white count a week after starting broad-spectrum antibiotics.',
    vitals: [v('T', '38.2', true), v('WBC', '18', true)],
    findings: ['Stool positive for C. difficile toxin.'],
    options: [
      { id: 'a', text: 'Clostridioides difficile colitis', correct: true },
      { id: 'b', text: 'Viral gastroenteritis', whyNot: 'A viral illness does not follow antibiotics with toxin-positive stool and a leukocytosis of 18.' },
      { id: 'c', text: 'Ischemic colitis', whyNot: 'Ischemic colitis causes bloody diarrhea in a vasculopath, not antibiotic-associated toxin-positive watery diarrhea.' },
      { id: 'd', text: 'Irritable bowel syndrome', whyNot: 'IBS has no fever, leukocytosis or a positive C. diff toxin.' },
    ],
    discriminator: 'Watery diarrhea with leukocytosis after antibiotics and a positive stool toxin is C. difficile colitis — stop the offending antibiotic and treat with oral vancomycin or fidaxomicin.',
    tags: { system: 'gi', complaint: 'diarrhea', rotation: ['im'], level: 'both' },
    difficultySeed: 0.75, source: [{ ref: 'IDSA/SHEA Clinical Practice Guidelines for C. difficile', year: 2021 }],
  },
  {
    itemId: 'colorectal-cancer-1', version: 1, type: 'one_liner', conceptId: 'colorectal-cancer',
    stem: '64 M with fatigue and iron-deficiency anemia, a change in bowel habit and occult blood in the stool; he has had no screening colonoscopy.',
    vitals: [v('Hb', '9.4', true)],
    findings: ['Microcytic indices; colonoscopy shows a right-sided mass.'],
    options: [
      { id: 'a', text: 'Colorectal cancer', correct: true },
      { id: 'b', text: 'Hemorrhoids', whyNot: 'Hemorrhoids cause bright-red rectal bleeding without iron-deficiency anemia and a colonic mass.' },
      { id: 'c', text: 'Peptic ulcer disease', whyNot: 'An upper GI ulcer can cause iron deficiency but not a right-sided colonic mass and change in bowel habit.' },
      { id: 'd', text: 'Diverticulosis', whyNot: 'Diverticular bleeding is painless and brisk, not chronic occult loss with a mass on colonoscopy.' },
    ],
    discriminator: 'Iron-deficiency anemia with occult GI blood loss and a change in bowel habit in an older adult is colorectal cancer until colonoscopy proves otherwise — new iron deficiency in a man or postmenopausal woman is GI cancer until excluded.',
    tags: { system: 'gi', complaint: 'anemia', rotation: ['im', 'fm', 'surg'], level: 'both' },
    difficultySeed: 0.7, source: [{ ref: 'USPSTF Recommendation: Colorectal Cancer Screening', year: 2021 }],
  },
  {
    itemId: 'pancreatic-cancer-1', version: 1, type: 'association', conceptId: 'pancreatic-cancer',
    stem: 'Painless jaundice with a palpable, non-tender gallbladder (Courvoisier sign) and weight loss in an older smoker.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Pancreatic head adenocarcinoma', correct: true },
      { id: 'b', text: 'Choledocholithiasis', whyNot: 'A stone-obstructed duct is usually painful with a scarred, non-distensible gallbladder — a painlessly distended gallbladder suggests malignant obstruction.' },
      { id: 'c', text: 'Viral hepatitis', whyNot: 'Hepatitis gives hepatocellular jaundice with high transaminases, not a palpable gallbladder and obstructive picture.' },
      { id: 'd', text: 'Gilbert syndrome', whyNot: 'Gilbert is a mild unconjugated hyperbilirubinemia with fasting/stress, not painless obstructive jaundice with weight loss.' },
    ],
    discriminator: 'Painless jaundice with a palpable non-tender gallbladder (Courvoisier) and weight loss is a pancreatic head cancer obstructing the bile duct — a stone would usually scar the gallbladder and hurt.',
    tags: { system: 'gi', complaint: 'buzzword', rotation: ['im', 'surg'], level: 'both', boards: ['step2'] },
    difficultySeed: 0.55, source: [{ ref: 'NCCN Guidelines: Pancreatic Adenocarcinoma', year: 2023 }],
  },

  /* ── Endocrine ── */
  {
    itemId: 'metabolic-syndrome-1', version: 1, type: 'one_liner', conceptId: 'metabolic-syndrome',
    stem: 'A patient has central obesity, a fasting glucose of 110, triglycerides of 200, HDL of 35 and blood pressure of 135/88.',
    vitals: [v('BP', '135/88', true), v('Waist', 'increased', true)],
    findings: [],
    options: [
      { id: 'a', text: 'Metabolic syndrome', correct: true },
      { id: 'b', text: 'Type 2 diabetes', whyNot: 'The glucose is impaired but not diabetic; the clustering of five risk components defines metabolic syndrome, not overt diabetes.' },
      { id: 'c', text: 'Cushing syndrome', whyNot: 'Cushing adds striae, proximal myopathy and cortisol excess; this is the common insulin-resistance cluster without hypercortisolism.' },
      { id: 'd', text: 'Hypothyroidism', whyNot: 'Hypothyroidism raises lipids but does not define the waist/glucose/BP/HDL cluster of metabolic syndrome.' },
    ],
    discriminator: 'Three or more of central obesity, high triglycerides, low HDL, raised blood pressure and impaired fasting glucose is metabolic syndrome — an insulin-resistance cluster that predicts cardiovascular and diabetes risk.',
    tags: { system: 'endocrine', complaint: 'risk factor', rotation: ['fm', 'im'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'AHA/NHLBI Scientific Statement on Metabolic Syndrome', year: 2005 }],
  },
  {
    itemId: 'cah-1', version: 1, type: 'association', conceptId: 'cah',
    stem: 'A newborn girl with ambiguous genitalia, and a salt-wasting crisis (hyponatremia, hyperkalemia, hypotension) in the first weeks, with elevated 17-hydroxyprogesterone.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Congenital adrenal hyperplasia (21-hydroxylase deficiency)', correct: true },
      { id: 'b', text: 'Androgen insensitivity syndrome', whyNot: 'AIS produces a phenotypic female with testes and no salt-wasting or raised 17-OHP.' },
      { id: 'c', text: 'Primary adrenal insufficiency (autoimmune)', whyNot: 'Autoimmune Addison is a disease of later life without virilization or raised 17-hydroxyprogesterone.' },
      { id: 'd', text: 'Hypothyroidism', whyNot: 'Congenital hypothyroidism causes lethargy and jaundice, not virilization with a salt-wasting adrenal crisis.' },
    ],
    discriminator: 'Virilization with salt-wasting and a high 17-hydroxyprogesterone is 21-hydroxylase deficiency CAH — the block shunts precursors to androgens while cortisol and aldosterone fail.',
    tags: { system: 'endocrine', complaint: 'buzzword', rotation: ['peds'], level: 'both', boards: ['step1'] },
    difficultySeed: 0.5, source: [{ ref: 'Endocrine Society Guideline on Congenital Adrenal Hyperplasia', year: 2018 }],
  },
  {
    itemId: 'hypoglycemia-1', version: 1, type: 'discriminator', conceptId: 'hypoglycemia',
    stem: 'A non-diabetic patient has documented hypoglycemia. Which lab pattern indicates surreptitious insulin injection rather than an insulinoma?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'High insulin with LOW C-peptide', correct: true },
      { id: 'b', text: 'High insulin with high C-peptide', whyNot: 'Endogenous overproduction (insulinoma or a sulfonylurea) raises insulin and C-peptide together — exogenous insulin suppresses C-peptide.' },
      { id: 'c', text: 'Low insulin and low C-peptide', whyNot: 'That is appropriate suppression, seen in non-insulin causes of hypoglycemia, not injected insulin.' },
      { id: 'd', text: 'High C-peptide with positive sulfonylurea screen', whyNot: 'That indicates a sulfonylurea, which drives endogenous insulin (high C-peptide), not injected insulin.' },
    ],
    discriminator: 'Hypoglycemia with high insulin but LOW C-peptide is exogenous insulin — the injected hormone lacks C-peptide, whereas an insulinoma or sulfonylurea raises both.',
    teachingPoint: 'Whipple triad — symptoms, documented low glucose, relief with glucose — defines true hypoglycemia before you work up the cause.',
    tags: { system: 'endocrine', complaint: 'hypoglycemia', rotation: ['im'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'Endocrine Society Guideline on Hypoglycemic Disorders', year: 2009 }],
  },

  /* ── Heme / Onc ── */
  {
    itemId: 'coag-labs-1', version: 1, type: 'discriminator', conceptId: 'coagulopathy-labs',
    stem: 'A patient bleeds with an isolated prolonged PTT (normal PT and platelets) that corrects on a mixing study, with a lifelong history of hemarthroses in a male.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Hemophilia (factor VIII or IX deficiency)', correct: true },
      { id: 'b', text: 'Vitamin K deficiency', whyNot: 'Vitamin K deficiency prolongs the PT first (factor VII has the shortest half-life), not an isolated PTT with hemarthroses.' },
      { id: 'c', text: 'Immune thrombocytopenia', whyNot: 'ITP causes mucocutaneous bleeding with low platelets and normal coagulation times, not an isolated long PTT.' },
      { id: 'd', text: 'A factor inhibitor (acquired)', whyNot: 'An inhibitor prolongs the PTT but does NOT correct on mixing — correction here indicates a factor deficiency.' },
    ],
    discriminator: 'An isolated prolonged PTT that corrects on mixing, with hemarthroses in a male, is hemophilia — a factor deficiency corrects on mixing, whereas an inhibitor does not.',
    teachingPoint: 'PT reflects the extrinsic/common path (warfarin, factor VII); PTT the intrinsic path (heparin, factors VIII/IX); both prolonged points to the common pathway or DIC.',
    tags: { system: 'heme_onc', complaint: 'bleeding', rotation: ['im', 'peds'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'WFH Guidelines for the Management of Hemophilia', year: 2020 }],
  },
  {
    itemId: 'dic-1', version: 1, type: 'one_liner', conceptId: 'dic',
    stem: 'A septic patient develops oozing from venipuncture sites and bruising, with a low platelet count, prolonged PT and PTT, low fibrinogen and a high D-dimer.',
    vitals: [], findings: ['Schistocytes on the smear.'],
    options: [
      { id: 'a', text: 'Disseminated intravascular coagulation', correct: true },
      { id: 'b', text: 'Immune thrombocytopenia', whyNot: 'ITP has isolated thrombocytopenia with normal coagulation times and fibrinogen, not the global consumption of DIC.' },
      { id: 'c', text: 'Thrombotic thrombocytopenic purpura', whyNot: 'TTP has a normal PT/PTT and fibrinogen; DIC consumes them and drops the fibrinogen.' },
      { id: 'd', text: 'Liver failure alone', whyNot: 'Liver disease prolongs the PT and can lower platelets, but the very high D-dimer with low fibrinogen and schistocytes marks active consumption.' },
    ],
    discriminator: 'Bleeding with low platelets, prolonged PT/PTT, low fibrinogen and a high D-dimer in a sick patient is DIC — simultaneous consumption of platelets and clotting factors, unlike the spared coagulation panel of TTP.',
    tags: { system: 'heme_onc', complaint: 'bleeding', rotation: ['im', 'em'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'ISTH Guidance on Diagnosis & Management of DIC', year: 2018 }],
  },
  {
    itemId: 'cord-compression-1', version: 1, type: 'cant_miss', conceptId: 'cord-compression',
    stem: 'A patient with known metastatic prostate cancer has progressive back pain, now with bilateral leg weakness, a sensory level and urinary retention. What must you do immediately?',
    vitals: [], findings: ['Hyperreflexia and up-going toes below the level.'],
    options: [
      { id: 'a', text: 'Emergent MRI of the whole spine and IV dexamethasone', correct: true },
      { id: 'b', text: 'Outpatient physiotherapy', whyNot: 'A cord under compression becomes permanently damaged within hours; conservative delay loses ambulation and continence.' },
      { id: 'c', text: 'Plain spine X-rays and discharge', whyNot: 'X-ray cannot show the cord compression, and discharge forfeits the treatment window.' },
      { id: 'd', text: 'Analgesia and reassess in a week', whyNot: 'Waiting a week on a compressed cord guarantees irreversible paraplegia.' },
    ],
    discriminator: 'Back pain with new bilateral leg weakness, a sensory level and sphincter dysfunction in a cancer patient is malignant cord compression — emergent MRI and steroids now, because the pre-treatment neurologic status predicts recovery.',
    tags: { system: 'heme_onc', complaint: 'back pain', rotation: ['em', 'im', 'neur'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'NICE Guideline: Metastatic Spinal Cord Compression', year: 2023 }],
  },
  {
    itemId: 'tumor-lysis-1', version: 1, type: 'one_liner', conceptId: 'tumor-lysis',
    stem: 'A patient with a bulky lymphoma, just after starting chemotherapy, develops acute kidney injury with high potassium, high phosphate, high uric acid and low calcium.',
    vitals: [v('K', '6.2', true), v('PO₄', '7.0', true)],
    findings: [],
    options: [
      { id: 'a', text: 'Tumor lysis syndrome', correct: true },
      { id: 'b', text: 'Contrast nephropathy', whyNot: 'Contrast AKI does not release potassium, phosphate and uric acid from lysed cells or drop the calcium.' },
      { id: 'c', text: 'Hypercalcemia of malignancy', whyNot: 'That raises calcium; tumor lysis LOWERS calcium as phosphate binds it.' },
      { id: 'd', text: 'Rhabdomyolysis', whyNot: 'Rhabdomyolysis raises CK with myoglobinuria; the uric acid surge after chemotherapy is tumor lysis.' },
    ],
    discriminator: 'AKI with high potassium, phosphate and uric acid and low calcium just after cytotoxic therapy for a bulky tumour is tumor lysis syndrome — prevent it with hydration and rasburicase/allopurinol.',
    tags: { system: 'heme_onc', complaint: 'electrolyte emergency', rotation: ['im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'Review: Tumor Lysis Syndrome (NEJM)', year: 2011 }],
  },
  {
    itemId: 'febrile-neutropenia-1', version: 1, type: 'tx_next_step', conceptId: 'febrile-neutropenia',
    stem: 'A patient on chemotherapy has a single fever of 38.5°C with an absolute neutrophil count of 400. What is the immediate step?',
    vitals: [v('T', '38.5', true), v('ANC', '400', true)],
    findings: [],
    options: [
      { id: 'a', text: 'Blood cultures then empiric broad-spectrum antibiotics (anti-pseudomonal) within an hour', correct: true },
      { id: 'b', text: 'Wait for a culture result before antibiotics', whyNot: 'A neutropenic host cannot mount a response; waiting on cultures risks rapid septic death, so treat empirically now.' },
      { id: 'c', text: 'Oral acetaminophen and observe at home', whyNot: 'Febrile neutropenia is an emergency; antipyretics without antibiotics ignore a potentially fatal infection.' },
      { id: 'd', text: 'Narrow-spectrum oral antibiotics only', whyNot: 'Empiric therapy must cover Pseudomonas and gram-negatives with a broad IV agent, not a narrow oral one.' },
    ],
    discriminator: 'A single fever with an ANC under 500 is febrile neutropenia — draw cultures and start empiric anti-pseudomonal antibiotics within the hour, because a neutropenic patient can deteriorate before cultures return.',
    tags: { system: 'heme_onc', complaint: 'fever', rotation: ['im', 'em'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'IDSA Guideline for Antimicrobial Use in Neutropenic Patients', year: 2010 }],
  },
  {
    itemId: 'transfusion-1', version: 1, type: 'discriminator', conceptId: 'transfusion-reactions',
    stem: 'Minutes into a red-cell transfusion a patient has fever, flank pain, dark urine and hypotension. Which reaction is this?',
    vitals: [v('T', '39.0', true), v('BP', '86/50', true)],
    findings: [],
    options: [
      { id: 'a', text: 'Acute hemolytic transfusion reaction (ABO incompatibility)', correct: true },
      { id: 'b', text: 'Febrile non-hemolytic reaction', whyNot: 'A febrile non-hemolytic reaction gives fever/chills without hemolysis, flank pain, hemoglobinuria or shock.' },
      { id: 'c', text: 'Allergic (urticarial) reaction', whyNot: 'Allergic reactions cause hives and, if severe, anaphylaxis — not hemoglobinuria and DIC from red-cell destruction.' },
      { id: 'd', text: 'TACO (circulatory overload)', whyNot: 'TACO causes dyspnea and hypertension from volume, not fever with flank pain and dark urine.' },
    ],
    discriminator: 'Fever, flank pain, hemoglobinuria and shock within minutes of a transfusion is an acute hemolytic (ABO-incompatible) reaction — stop the transfusion immediately and support the kidneys and pressure.',
    tags: { system: 'heme_onc', complaint: 'transfusion reaction', rotation: ['im', 'surg'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'AABB Technical Manual', year: 2020 }],
  },

  /* ── Infectious ── */
  {
    itemId: 'sepsis-recognition-1', version: 1, type: 'one_liner', conceptId: 'sepsis-recognition',
    stem: 'An elderly man with a urinary source has confusion, a respiratory rate of 24, blood pressure of 96/60 and a lactate of 3.2.',
    vitals: [v('RR', '24', true), v('BP', '96/60', true), v('Lactate', '3.2', true)],
    findings: [],
    options: [
      { id: 'a', text: 'Sepsis', correct: true },
      { id: 'b', text: 'Simple urinary tract infection', whyNot: 'A simple UTI has no organ dysfunction; confusion, tachypnea, hypotension and a raised lactate mark sepsis.' },
      { id: 'c', text: 'Dehydration', whyNot: 'Dehydration does not itself raise the lactate to 3.2 with an infective source and altered mentation.' },
      { id: 'd', text: 'Delirium of unknown cause', whyNot: 'The confusion here is an organ-dysfunction marker of sepsis from a urinary source, not idiopathic delirium.' },
    ],
    discriminator: 'Infection plus new organ dysfunction — altered mentation, tachypnea, hypotension or a raised lactate — is sepsis; the qSOFA/organ-dysfunction signs, not the fever, define it.',
    tags: { system: 'infectious', complaint: 'sepsis', rotation: ['em', 'im'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'Surviving Sepsis Campaign Guidelines', year: 2021 }],
  },
  {
    itemId: 'sepsis-bundle-1', version: 1, type: 'tx_sequencing', conceptId: 'sepsis-bundle',
    stem: 'A patient meets criteria for septic shock. What belongs in the first-hour bundle?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Lactate, blood cultures before antibiotics, broad-spectrum antibiotics, and 30 mL/kg crystalloid for hypotension/lactate ≥4', correct: true },
      { id: 'b', text: 'Antibiotics only after imaging localises the source', whyNot: 'Empiric antibiotics must not wait for imaging in shock — every hour of delay raises mortality.' },
      { id: 'c', text: 'Vasopressors first, before any fluids', whyNot: 'Fluid resuscitation comes first; norepinephrine is added if hypotension persists after adequate fluids.' },
      { id: 'd', text: 'Withhold cultures to save time', whyNot: 'Cultures are drawn before antibiotics when it does not delay them, to guide later de-escalation.' },
    ],
    discriminator: 'The sepsis first-hour bundle is measure lactate, draw cultures before antibiotics, give broad-spectrum antibiotics, and resuscitate with 30 mL/kg crystalloid — antibiotics and fluids do not wait on imaging.',
    tags: { system: 'infectious', complaint: 'sepsis', rotation: ['em', 'im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'Surviving Sepsis Campaign Hour-1 Bundle', year: 2021 }],
  },
  {
    itemId: 'infectious-diarrhea-1', version: 1, type: 'discriminator', conceptId: 'infectious-diarrhea',
    stem: 'A patient has acute diarrhea. Which feature most indicates an inflammatory (invasive) bacterial cause rather than a watery/toxin-mediated one?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Bloody stools with fever and fecal leukocytes', correct: true },
      { id: 'b', text: 'Large-volume watery stools without blood', whyNot: 'Voluminous watery diarrhea is toxin/secretory (e.g., cholera, viral), not invasive inflammatory disease.' },
      { id: 'c', text: 'Vomiting within hours of a meal', whyNot: 'Rapid post-meal vomiting is preformed-toxin food poisoning (S. aureus, B. cereus), not invasive colitis.' },
      { id: 'd', text: 'Resolution in 24 hours', whyNot: 'Quick self-resolution favours a viral or toxin cause, not invasive bacterial dysentery.' },
    ],
    discriminator: 'Bloody diarrhea with fever and fecal leukocytes is inflammatory/invasive (Shigella, Salmonella, Campylobacter, EHEC) — watery, non-bloody diarrhea points to a toxin or virus.',
    teachingPoint: 'Avoid antibiotics in suspected EHEC (O157:H7) — they raise the risk of hemolytic uremic syndrome.',
    tags: { system: 'infectious', complaint: 'diarrhea', rotation: ['im', 'em', 'fm'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'IDSA Guideline on Infectious Diarrhea', year: 2017 }],
  },
  {
    itemId: 'asymptomatic-bacteriuria-1', version: 1, type: 'tx_threshold', conceptId: 'asymptomatic-bacteriuria',
    stem: 'A urine culture grows bacteria in an asymptomatic patient. In which situation is treatment indicated?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Pregnancy (or before an invasive urologic procedure)', correct: true },
      { id: 'b', text: 'An elderly nursing-home resident with no symptoms', whyNot: 'Treating asymptomatic bacteriuria in elders drives resistance without benefit — treat only if symptomatic.' },
      { id: 'c', text: 'A patient with a chronic indwelling catheter', whyNot: 'Catheter bacteriuria is expected and is not treated unless the patient is symptomatic.' },
      { id: 'd', text: 'A well diabetic outpatient', whyNot: 'Diabetes alone is not an indication; asymptomatic bacteriuria in a stable diabetic is not treated.' },
    ],
    discriminator: 'Asymptomatic bacteriuria is treated only in pregnancy and before urologic procedures that breach the mucosa — everywhere else, treating it causes harm without benefit.',
    tags: { system: 'infectious', complaint: 'bacteriuria', rotation: ['im', 'fm', 'obgyn'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'IDSA Guideline on Asymptomatic Bacteriuria', year: 2019 }],
  },
  {
    itemId: 'hsv-encephalitis-1', version: 1, type: 'one_liner', conceptId: 'hsv-encephalitis',
    stem: 'A patient with fever, confusion, personality change and a focal seizure; MRI shows temporal-lobe changes and the CSF has lymphocytes with red cells.',
    vitals: [v('T', '38.8', true)],
    findings: ['EEG: temporal periodic discharges; CSF HSV PCR pending.'],
    options: [
      { id: 'a', text: 'Herpes simplex encephalitis', correct: true },
      { id: 'b', text: 'Bacterial meningitis', whyNot: 'Bacterial meningitis is a neutrophilic CSF with low glucose and meningism, not temporal-lobe encephalitis with focal seizures.' },
      { id: 'c', text: 'Ischemic stroke', whyNot: 'A stroke is a sudden painless deficit without fever, CSF pleocytosis and temporal-lobe inflammation.' },
      { id: 'd', text: 'Alcohol withdrawal', whyNot: 'Withdrawal causes tremor and seizures without fever, focal temporal MRI change and CSF pleocytosis.' },
    ],
    discriminator: 'Fever with encephalopathy, focal (temporal) signs and a lymphocytic CSF is HSV encephalitis — start empiric acyclovir immediately, because waiting for the PCR costs neurons.',
    tags: { system: 'infectious', complaint: 'confusion', rotation: ['em', 'im', 'neur'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'IDSA Guideline on Encephalitis', year: 2008 }],
  },
  {
    itemId: 'cellulitis-erysipelas-1', version: 1, type: 'discriminator', conceptId: 'cellulitis-vs-erysipelas',
    stem: 'A patient has a red, warm, tender leg. Which feature points to erysipelas rather than ordinary cellulitis?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'A raised, sharply demarcated border', correct: true },
      { id: 'b', text: 'Poorly defined, flat spreading margins', whyNot: 'Ill-defined flat margins describe cellulitis; erysipelas is raised and sharply bordered.' },
      { id: 'c', text: 'Fluctuance and pointing', whyNot: 'Fluctuance signals an abscess needing incision and drainage, not the superficial dermal lymphatic infection of erysipelas.' },
      { id: 'd', text: 'Crepitus and pain out of proportion', whyNot: 'Those are red flags for necrotizing fasciitis, not the benign raised border of erysipelas.' },
    ],
    discriminator: 'Erysipelas is a superficial dermal-lymphatic streptococcal infection with a raised, sharply demarcated border; cellulitis is deeper with flat, ill-defined margins, and fluctuance means an abscess to drain.',
    tags: { system: 'infectious', complaint: 'skin infection', rotation: ['em', 'fm', 'im'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'IDSA Practice Guidelines for Skin & Soft Tissue Infections', year: 2014 }],
  },

  /* ── Dermatology ── */
  {
    itemId: 'psoriasis-1', version: 1, type: 'one_liner', conceptId: 'psoriasis',
    stem: 'A patient with well-demarcated erythematous plaques topped by silvery scale over the elbows, knees and scalp, with pitted nails; scratching the scale causes pinpoint bleeding.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Plaque psoriasis', correct: true },
      { id: 'b', text: 'Atopic dermatitis', whyNot: 'Atopic eczema favours the flexures with ill-defined, oozing, intensely itchy patches, not silvery plaques on extensor surfaces with nail pitting.' },
      { id: 'c', text: 'Tinea corporis', whyNot: 'Ringworm is an annular scaly plaque with central clearing and positive KOH, not symmetric silvery extensor plaques.' },
      { id: 'd', text: 'Seborrheic dermatitis', whyNot: 'Seborrhea is greasy yellow scale in the nasolabial folds and scalp, not thick silvery extensor plaques with Auspitz sign.' },
    ],
    discriminator: 'Silvery-scaled, well-demarcated plaques on extensor surfaces with nail pitting and an Auspitz sign is plaque psoriasis — an immune-mediated hyperproliferative disorder.',
    tags: { system: 'dermatology', complaint: 'rash', rotation: ['fm', 'im'], level: 'both' },
    difficultySeed: 0.7, source: [{ ref: 'AAD/NPF Guidelines of Care for Psoriasis', year: 2021 }],
  },
  {
    itemId: 'atopic-dermatitis-1', version: 1, type: 'one_liner', conceptId: 'atopic-dermatitis',
    stem: 'A child with recurrent intensely itchy, ill-defined red patches in the antecubital and popliteal flexures, with dry skin and a history of asthma and hay fever.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Atopic dermatitis', correct: true },
      { id: 'b', text: 'Psoriasis', whyNot: 'Psoriasis gives silvery extensor plaques, not itchy flexural eczema in an atopic child.' },
      { id: 'c', text: 'Contact dermatitis', whyNot: 'Contact dermatitis is localised to the area of exposure with a matching pattern, not chronic flexural atopic disease.' },
      { id: 'd', text: 'Scabies', whyNot: 'Scabies itches worst at night with burrows in the web spaces, not the flexural eczema of atopy.' },
    ],
    discriminator: 'Chronic itchy flexural eczema with dry skin in a child with asthma and allergic rhinitis is atopic dermatitis — part of the atopic triad, driven by a skin-barrier defect.',
    tags: { system: 'dermatology', complaint: 'rash', rotation: ['peds', 'fm'], level: 'both' },
    difficultySeed: 0.7, source: [{ ref: 'AAD Guidelines of Care for Atopic Dermatitis', year: 2023 }],
  },
  {
    itemId: 'erythema-nodosum-1', version: 1, type: 'association', conceptId: 'erythema-nodosum',
    stem: 'Tender, red, raised nodules over both shins in a young woman, with recent sarcoidosis / inflammatory bowel disease / streptococcal infection.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Erythema nodosum', correct: true },
      { id: 'b', text: 'Cellulitis', whyNot: 'Cellulitis is a single warm spreading plaque with fever, not symmetric tender nodules over both shins.' },
      { id: 'c', text: 'Erythema multiforme', whyNot: 'EM makes target lesions on the palms/soles, not tender pretibial nodules.' },
      { id: 'd', text: 'Nodular vasculitis', whyNot: 'Nodular vasculitis ulcerates on the calves; erythema nodosum is a non-ulcerating septal panniculitis of the shins.' },
    ],
    discriminator: 'Tender red nodules over both shins are erythema nodosum — a reactive panniculitis flagging sarcoidosis, IBD, streptococcal infection, TB, or a drug.',
    tags: { system: 'dermatology', complaint: 'buzzword', rotation: ['im', 'fm'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'Review: Erythema Nodosum (Am Fam Physician)', year: 2019 }],
  },
  {
    itemId: 'acanthosis-1', version: 1, type: 'association', conceptId: 'acanthosis-nigricans',
    stem: 'Velvety, hyperpigmented thickening of the skin in the axillae and posterior neck.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Insulin resistance (or, if abrupt/extensive, GI malignancy)', correct: true },
      { id: 'b', text: 'Tinea versicolor', whyNot: 'Tinea versicolor is scaly hypo/hyperpigmented macules with a positive KOH, not velvety flexural thickening.' },
      { id: 'c', text: 'Addison hyperpigmentation', whyNot: 'Addison darkens creases and mucosa diffusely from ACTH, not the velvety flexural plaques of acanthosis.' },
      { id: 'd', text: 'Contact dermatitis', whyNot: 'Contact dermatitis is an itchy inflammatory reaction to an allergen, not asymptomatic velvety hyperpigmentation.' },
    ],
    discriminator: 'Velvety hyperpigmented plaques in the axillae and neck are acanthosis nigricans — usually a marker of insulin resistance, and if sudden and florid, a paraneoplastic sign of GI adenocarcinoma.',
    tags: { system: 'dermatology', complaint: 'buzzword', rotation: ['fm', 'im'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.5, source: [{ ref: 'Review: Acanthosis Nigricans (JAAD)', year: 2020 }],
  },
  {
    itemId: 'ace-angioedema-1', version: 1, type: 'one_liner', conceptId: 'ace-angioedema',
    stem: 'A patient develops non-itchy swelling of the lips and tongue without hives, months after starting an ACE inhibitor for hypertension.',
    vitals: [], findings: ['No urticaria; airway patent but tongue swelling progressing.'],
    options: [
      { id: 'a', text: 'ACE-inhibitor–induced angioedema (bradykinin-mediated)', correct: true },
      { id: 'b', text: 'Allergic (histaminergic) angioedema', whyNot: 'Allergic angioedema comes with urticaria and responds to antihistamines/epinephrine; the drug-linked, hive-free swelling here is bradykinin-mediated.' },
      { id: 'c', text: 'Anaphylaxis', whyNot: 'Anaphylaxis has hives, wheeze and hypotension across systems; isolated hive-free lip/tongue swelling on an ACE inhibitor is bradykinin angioedema.' },
      { id: 'd', text: 'Cellulitis of the lip', whyNot: 'Cellulitis is warm, tender and febrile, not painless non-pitting angioedema linked to a drug.' },
    ],
    discriminator: 'Non-urticarial lip and tongue swelling on an ACE inhibitor is bradykinin-mediated angioedema — stop the drug and protect the airway; antihistamines and epinephrine are far less effective than in allergic swelling.',
    tags: { system: 'dermatology', complaint: 'swelling', rotation: ['em', 'im'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'AAAAI/ACAAI Practice Parameter on Angioedema', year: 2020 }],
  },
  {
    itemId: 'erythema-multiforme-1', version: 1, type: 'association', conceptId: 'erythema-multiforme',
    stem: 'Symmetric target (iris) lesions with a dusky center on the palms and soles, following a herpes simplex outbreak.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Erythema multiforme', correct: true },
      { id: 'b', text: 'Urticaria', whyNot: 'Hives are transient wheals that move within 24 hours, not fixed target lesions with a dusky center.' },
      { id: 'c', text: 'Stevens–Johnson syndrome', whyNot: 'SJS has extensive mucosal erosions and skin sloughing with systemic toxicity; classic EM is target lesions from HSV with limited mucosal involvement.' },
      { id: 'd', text: 'Erythema migrans', whyNot: 'Erythema migrans is a single expanding ring after a tick bite, not symmetric acral target lesions after HSV.' },
    ],
    discriminator: 'Symmetric acral target lesions after herpes simplex are erythema multiforme — most often HSV-triggered, distinct from the mucosa-dominant, drug-triggered SJS/TEN spectrum.',
    tags: { system: 'dermatology', complaint: 'buzzword', rotation: ['fm', 'em'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'Review: Erythema Multiforme (Am Fam Physician)', year: 2019 }],
  },

  /* ── Psychiatry ── */
  {
    itemId: 'psychosis-timeline-1', version: 1, type: 'discriminator', conceptId: 'psychosis-timeline',
    stem: 'A young adult has had delusions and disorganized speech. Which duration makes the diagnosis schizophrenia rather than a shorter-course disorder?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Continuous signs for at least 6 months', correct: true },
      { id: 'b', text: 'Symptoms for 2 weeks', whyNot: 'Under a month of psychosis with a stressor is brief psychotic disorder, not schizophrenia.' },
      { id: 'c', text: 'Symptoms for 2 months', whyNot: 'One to six months of the full picture is schizophreniform disorder — schizophrenia requires ≥6 months.' },
      { id: 'd', text: 'Any duration if hallucinations are present', whyNot: 'Duration is essential to the diagnosis; hallucinations alone do not make schizophrenia.' },
    ],
    discriminator: 'Schizophrenia requires ≥6 months of continuous signs; brief psychotic disorder is under a month and schizophreniform is 1–6 months — the timeline defines which diagnosis applies.',
    tags: { system: 'psychiatry', complaint: 'psychosis', rotation: ['psych'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'DSM-5-TR', year: 2022 }],
  },
  {
    itemId: 'anxiety-differential-1', version: 1, type: 'discriminator', conceptId: 'anxiety-differential',
    stem: 'A patient has recurrent, unexpected episodes of intense fear peaking within minutes with palpitations, chest tightness and a fear of dying, then worries about the next attack. Which disorder?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Panic disorder', correct: true },
      { id: 'b', text: 'Generalized anxiety disorder', whyNot: 'GAD is persistent excessive worry across domains for ≥6 months, not discrete peaking panic attacks.' },
      { id: 'c', text: 'Post-traumatic stress disorder', whyNot: 'PTSD follows trauma with re-experiencing, avoidance and hyperarousal, not spontaneous panic attacks with anticipatory worry.' },
      { id: 'd', text: 'Obsessive–compulsive disorder', whyNot: 'OCD is intrusive obsessions and compulsions performed to reduce anxiety, not recurrent unexpected panic attacks.' },
    ],
    discriminator: 'Recurrent unexpected attacks peaking within minutes plus worry about further attacks is panic disorder — GAD is chronic diffuse worry, PTSD follows trauma, and OCD is obsessions with compulsions.',
    tags: { system: 'psychiatry', complaint: 'anxiety', rotation: ['psych', 'fm'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'DSM-5-TR', year: 2022 }],
  },
  {
    itemId: 'dementia-types-1', version: 1, type: 'discriminator', conceptId: 'dementia-types',
    stem: 'An older adult with cognitive decline also has visual hallucinations, fluctuating attention, spontaneous parkinsonism and severe sensitivity to antipsychotics. Which dementia?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Dementia with Lewy bodies', correct: true },
      { id: 'b', text: 'Alzheimer disease', whyNot: 'Alzheimer is a gradual amnestic decline without early hallucinations, fluctuations or parkinsonism.' },
      { id: 'c', text: 'Vascular dementia', whyNot: 'Vascular dementia declines stepwise with focal deficits and vascular risk, not fluctuating cognition with visual hallucinations and parkinsonism.' },
      { id: 'd', text: 'Frontotemporal dementia', whyNot: 'FTD presents with early personality/behaviour change or aphasia, not visual hallucinations with parkinsonism and antipsychotic sensitivity.' },
    ],
    discriminator: 'Fluctuating cognition with visual hallucinations, spontaneous parkinsonism and antipsychotic sensitivity is dementia with Lewy bodies — the antipsychotic sensitivity is a dangerous, distinctive clue.',
    tags: { system: 'psychiatry', complaint: 'cognitive decline', rotation: ['psych', 'neur', 'im'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'DLB Consortium Diagnostic Criteria', year: 2017 }],
  },
  {
    itemId: 'somatic-spectrum-1', version: 1, type: 'discriminator', conceptId: 'somatic-spectrum',
    stem: 'A patient intentionally produces symptoms (e.g., injecting insulin) with no external reward, seeking the sick role. Which diagnosis?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Factitious disorder', correct: true },
      { id: 'b', text: 'Malingering', whyNot: 'Malingering feigns illness for an external gain (money, drugs, avoiding work); factitious disorder is for the sick role itself.' },
      { id: 'c', text: 'Somatic symptom disorder', whyNot: 'Somatic symptom disorder is genuine distressing symptoms with excessive thoughts — the symptoms are not intentionally produced.' },
      { id: 'd', text: 'Conversion disorder', whyNot: 'Conversion (functional neurological) symptoms are involuntary neurologic deficits, not deliberately produced illness.' },
    ],
    discriminator: 'Intentionally producing illness with no external reward, to be a patient, is factitious disorder — malingering seeks external gain, and somatic/conversion symptoms are not deliberately produced.',
    tags: { system: 'psychiatry', complaint: 'somatic', rotation: ['psych', 'im'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'DSM-5-TR', year: 2022 }],
  },
  {
    itemId: 'adhd-1', version: 1, type: 'one_liner', conceptId: 'adhd',
    stem: 'A 7-year-old has persistent inattention, hyperactivity and impulsivity for over six months, present both at school and at home, impairing learning, with onset before age 12.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Attention-deficit/hyperactivity disorder', correct: true },
      { id: 'b', text: 'Normal age-appropriate behaviour', whyNot: 'Normal activity does not cross settings and impair function for months with onset before 12.' },
      { id: 'c', text: 'Oppositional defiant disorder', whyNot: 'ODD is a pattern of defiant, hostile behaviour toward authority, not the inattention/hyperactivity of ADHD.' },
      { id: 'd', text: 'Absence epilepsy', whyNot: 'Absence seizures are brief staring spells with EEG 3-Hz spike-and-wave, not pervasive inattention and hyperactivity across settings.' },
    ],
    discriminator: 'Pervasive inattention and hyperactivity/impulsivity across two or more settings for ≥6 months, beginning before age 12 and impairing function, is ADHD — the cross-setting impairment is required.',
    tags: { system: 'psychiatry', complaint: 'behaviour', rotation: ['peds', 'psych', 'fm'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'AAP Clinical Practice Guideline for ADHD', year: 2019 }],
  },
  {
    itemId: 'autism-1', version: 1, type: 'one_liner', conceptId: 'autism',
    stem: 'A 3-year-old has persistent deficits in social communication and reciprocity with restricted, repetitive behaviours and insistence on sameness, present from early childhood.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Autism spectrum disorder', correct: true },
      { id: 'b', text: 'Isolated language delay', whyNot: 'A pure language delay lacks the social-reciprocity deficits and restricted, repetitive behaviours of autism.' },
      { id: 'c', text: 'Hearing impairment', whyNot: 'Hearing loss impairs speech but not social reciprocity and repetitive behaviours — check hearing, but it is not the diagnosis here.' },
      { id: 'd', text: 'ADHD', whyNot: 'ADHD is inattention and hyperactivity without the core social-communication deficits and restricted interests of autism.' },
    ],
    discriminator: 'Early, persistent social-communication deficits with restricted, repetitive behaviours and insistence on sameness is autism spectrum disorder — the social-reciprocity deficit is the core.',
    tags: { system: 'psychiatry', complaint: 'development', rotation: ['peds', 'psych'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'DSM-5-TR', year: 2022 }],
  },
  {
    itemId: 'anorexia-bulimia-1', version: 1, type: 'discriminator', conceptId: 'anorexia-vs-bulimia',
    stem: 'Which single feature most distinguishes anorexia nervosa from bulimia nervosa?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Significantly low body weight', correct: true },
      { id: 'b', text: 'Binge eating episodes', whyNot: 'Binges occur in both (the binge-purge subtype of anorexia and in bulimia); they do not separate them.' },
      { id: 'c', text: 'Self-induced vomiting', whyNot: 'Purging occurs in both disorders; the defining difference is body weight.' },
      { id: 'd', text: 'Fear of gaining weight', whyNot: 'Both share intense fear of weight gain and body-image disturbance; only anorexia requires a significantly low weight.' },
    ],
    discriminator: 'A significantly low body weight defines anorexia nervosa; bulimia nervosa occurs at a normal or higher weight with recurrent binge–purge cycles — the weight, not the purging, separates them.',
    tags: { system: 'psychiatry', complaint: 'eating disorder', rotation: ['psych', 'fm'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'DSM-5-TR', year: 2022 }],
  },

  /* ── Reproductive ── */
  {
    itemId: 'postmenopausal-bleeding-1', version: 1, type: 'cant_miss', conceptId: 'postmenopausal-bleeding',
    stem: 'A 60-year-old, 8 years past menopause, has new vaginal bleeding. What must be excluded, and how?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Endometrial cancer — with endometrial biopsy (and/or transvaginal ultrasound)', correct: true },
      { id: 'b', text: 'Atrophic vaginitis — reassure without evaluation', whyNot: 'Atrophy is common, but you cannot attribute postmenopausal bleeding to it until cancer is excluded by sampling.' },
      { id: 'c', text: 'Normal menstruation', whyNot: 'There is no menstruation years after menopause; any bleeding is abnormal and needs work-up.' },
      { id: 'd', text: 'Fibroids — no further testing', whyNot: 'Fibroids rarely bleed after menopause; new bleeding still requires exclusion of endometrial cancer.' },
    ],
    discriminator: 'Any postmenopausal bleeding is endometrial cancer until proven otherwise — evaluate with endometrial biopsy or transvaginal ultrasound, never reassurance alone.',
    tags: { system: 'reproductive', complaint: 'vaginal bleeding', rotation: ['obgyn', 'fm'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'ACOG Committee Opinion: Postmenopausal Bleeding', year: 2018 }],
  },
  {
    itemId: 'cervical-screening-1', version: 1, type: 'tx_threshold', conceptId: 'cervical-screening',
    stem: 'At what age does cervical cancer screening (cytology) generally begin for an average-risk person?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Age 21', correct: true },
      { id: 'b', text: 'At first sexual activity', whyNot: 'Screening is not tied to sexual debut; transient HPV in adolescents clears, so cytology starts at 21.' },
      { id: 'c', text: 'Age 30', whyNot: 'Cytology begins at 21; primary HPV testing options begin later, but 30 is not the start of screening.' },
      { id: 'd', text: 'Age 40', whyNot: 'That is far too late — invasive cervical cancer would be missed for two decades.' },
    ],
    discriminator: 'Cervical cancer screening starts at age 21 regardless of sexual history — younger HPV infections usually clear, so earlier testing causes harm without benefit.',
    tags: { system: 'reproductive', complaint: 'screening', rotation: ['obgyn', 'fm'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'USPSTF Recommendation: Cervical Cancer Screening', year: 2018 }],
  },
  {
    itemId: 'breast-mass-1', version: 1, type: 'discriminator', conceptId: 'breast-mass',
    stem: 'Which single feature of a breast mass most raises concern for malignancy rather than a benign fibroadenoma?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'A hard, fixed, irregular mass with skin dimpling', correct: true },
      { id: 'b', text: 'A smooth, mobile, rubbery mass in a young woman', whyNot: 'That describes a fibroadenoma; mobility and smooth borders favour benign disease.' },
      { id: 'c', text: 'Cyclic tenderness', whyNot: 'Cyclic tenderness suggests fibrocystic change, not cancer.' },
      { id: 'd', text: 'Bilateral nodularity', whyNot: 'Diffuse bilateral nodularity is fibrocystic change, not a discrete malignant mass.' },
    ],
    discriminator: 'A hard, fixed, irregular mass with skin or nipple retraction is worrying for cancer; a smooth, mobile, rubbery mass in a young woman is a fibroadenoma — mobility and margins guide the work-up.',
    teachingPoint: 'Any dominant mass warrants triple assessment: exam, imaging (ultrasound ± mammography), and tissue.',
    tags: { system: 'reproductive', complaint: 'breast mass', rotation: ['surg', 'obgyn', 'fm'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'NCCN Guidelines: Breast Cancer Screening & Diagnosis', year: 2023 }],
  },
  {
    itemId: 'pcos-1', version: 1, type: 'one_liner', conceptId: 'pcos',
    stem: 'A 24-year-old with irregular infrequent periods, acne and hirsutism, mildly elevated androgens, and polycystic ovaries on ultrasound.',
    vitals: [v('BMI', 'raised', true)],
    findings: ['Excludes thyroid, prolactin and non-classic CAH.'],
    options: [
      { id: 'a', text: 'Polycystic ovary syndrome', correct: true },
      { id: 'b', text: 'Cushing syndrome', whyNot: 'Cushing adds striae, proximal myopathy and cortisol excess; PCOS is the common hyperandrogenic anovulation without hypercortisolism.' },
      { id: 'c', text: 'Androgen-secreting tumour', whyNot: 'A tumour causes rapid, severe virilization with very high androgens, not the gradual mild hyperandrogenism of PCOS.' },
      { id: 'd', text: 'Hypothyroidism', whyNot: 'Hypothyroidism disturbs cycles but does not cause hyperandrogenism with polycystic ovaries.' },
    ],
    discriminator: 'Oligo-ovulation, clinical/biochemical hyperandrogenism and polycystic ovaries (any two, others excluded) is PCOS by Rotterdam criteria — an insulin-resistant anovulatory syndrome.',
    tags: { system: 'reproductive', complaint: 'oligomenorrhea', rotation: ['obgyn', 'fm', 'im'], level: 'both' },
    difficultySeed: 0.65, source: [{ ref: 'International Evidence-based Guideline for PCOS', year: 2023 }],
  },
  {
    itemId: 'amenorrhea-1', version: 1, type: 'discriminator', conceptId: 'amenorrhea-workup',
    stem: 'After excluding pregnancy in a patient with secondary amenorrhea, which first test best orients the work-up?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'TSH, prolactin, and FSH (with a progesterone challenge)', correct: true },
      { id: 'b', text: 'Immediate pelvic MRI', whyNot: 'Imaging comes after the hormonal screen localises the problem; MRI first is premature.' },
      { id: 'c', text: 'Karyotype in everyone', whyNot: 'Karyotype is reserved for primary amenorrhea or suspected gonadal dysgenesis, not the routine secondary work-up.' },
      { id: 'd', text: 'Endometrial biopsy', whyNot: 'Biopsy evaluates bleeding/hyperplasia, not the cause of absent menses.' },
    ],
    discriminator: 'Secondary amenorrhea (after excluding pregnancy) is worked up with TSH, prolactin and FSH — separating thyroid/prolactin causes from ovarian failure (high FSH) versus central/outflow problems.',
    tags: { system: 'reproductive', complaint: 'amenorrhea', rotation: ['obgyn', 'im'], level: 'clerkship' },
    difficultySeed: 0.55, source: [{ ref: 'ASRM Practice Committee: Amenorrhea', year: 2008 }],
  },
  {
    itemId: 'vaginitis-1', version: 1, type: 'discriminator', conceptId: 'vaginitis',
    stem: 'A thin, off-white, malodorous ("fishy") discharge with a vaginal pH above 4.5 and clue cells on microscopy is which vaginitis?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Bacterial vaginosis', correct: true },
      { id: 'b', text: 'Vulvovaginal candidiasis', whyNot: 'Candida gives thick "cottage-cheese" discharge with itching, a normal pH and hyphae, not clue cells and a fishy odour.' },
      { id: 'c', text: 'Trichomoniasis', whyNot: 'Trichomonas gives a frothy green-yellow discharge with motile flagellates and a strawberry cervix, not clue cells.' },
      { id: 'd', text: 'Atrophic vaginitis', whyNot: 'Atrophy is a postmenopausal dryness, not a fishy discharge with clue cells and a positive whiff test.' },
    ],
    discriminator: 'Thin fishy discharge with pH > 4.5, clue cells and a positive whiff test is bacterial vaginosis; candida is itchy and thick with a normal pH, and trichomonas is frothy with motile organisms.',
    tags: { system: 'reproductive', complaint: 'discharge', rotation: ['obgyn', 'fm'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'CDC Sexually Transmitted Infections Treatment Guidelines', year: 2021 }],
  },
  {
    itemId: 'syphilis-1', version: 1, type: 'association', conceptId: 'syphilis-stages',
    stem: 'A single painless genital ulcer (chancre) with a clean base and non-tender regional lymphadenopathy.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Primary syphilis', correct: true },
      { id: 'b', text: 'Chancroid', whyNot: 'Chancroid (H. ducreyi) is a PAINFUL ulcer with a ragged base and tender suppurative nodes — syphilis is painless with a clean base.' },
      { id: 'c', text: 'Genital herpes', whyNot: 'HSV causes painful grouped vesicles and ulcers, not a single painless indurated chancre.' },
      { id: 'd', text: 'Lymphogranuloma venereum', whyNot: 'LGV gives a small transient ulcer then large painful buboes; the solitary painless clean chancre is primary syphilis.' },
    ],
    discriminator: 'A single painless genital ulcer with a clean, indurated base is the chancre of primary syphilis — painlessness separates it from the painful ulcers of chancroid and herpes.',
    teachingPoint: 'Secondary syphilis brings a rash including the palms and soles; tertiary brings gummas, aortitis and neurosyphilis.',
    tags: { system: 'reproductive', complaint: 'buzzword', rotation: ['fm', 'im', 'obgyn'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.55, source: [{ ref: 'CDC Sexually Transmitted Infections Treatment Guidelines', year: 2021 }],
  },
  {
    itemId: 'contraception-ci-1', version: 1, type: 'tx_contraindication', conceptId: 'contraception-contraindication',
    stem: 'For which patient is a combined (estrogen-containing) oral contraceptive contraindicated?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'A woman with migraine WITH aura', correct: true },
      { id: 'b', text: 'A healthy 24-year-old non-smoker', whyNot: 'A young healthy non-smoker is an ideal candidate for combined contraception.' },
      { id: 'c', text: 'A woman with well-controlled asthma', whyNot: 'Asthma is not a contraindication to estrogen-containing contraception.' },
      { id: 'd', text: 'A woman with iron-deficiency anemia', whyNot: 'Combined pills can actually reduce menstrual blood loss; anemia is not a contraindication.' },
    ],
    discriminator: 'Estrogen-containing contraception is contraindicated in migraine with aura (and in smokers over 35, prior VTE, or uncontrolled hypertension) because estrogen raises the ischemic-stroke and clot risk.',
    tags: { system: 'reproductive', complaint: 'contraception', rotation: ['obgyn', 'fm'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'CDC U.S. Medical Eligibility Criteria for Contraceptive Use', year: 2024 }],
  },

  /* ── Multisystem ── */
  {
    itemId: 'shock-types-1', version: 1, type: 'discriminator', conceptId: 'shock-types',
    stem: 'A hypotensive patient has warm extremities, a wide pulse pressure, low systemic vascular resistance and a high cardiac output. Which shock category?',
    vitals: [v('BP', '82/40', true)],
    findings: [],
    options: [
      { id: 'a', text: 'Distributive shock (e.g., septic)', correct: true },
      { id: 'b', text: 'Hypovolemic shock', whyNot: 'Hypovolemia gives cold clamped extremities with high SVR and low output, not the warm, vasodilated high-output picture.' },
      { id: 'c', text: 'Cardiogenic shock', whyNot: 'Cardiogenic shock has low output with high filling pressures and cold periphery, not warm high-output vasodilation.' },
      { id: 'd', text: 'Obstructive shock', whyNot: 'Obstructive shock (tamponade, tension pneumothorax, massive PE) impairs filling with high SVR, not warm distributive vasodilation.' },
    ],
    discriminator: 'Warm extremities with low SVR and high cardiac output is distributive (septic/anaphylactic/neurogenic) shock — hypovolemic and cardiogenic shock are cold with high SVR and low output.',
    tags: { system: 'multisystem', complaint: 'shock', rotation: ['em', 'im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'Review: Classification & Management of Shock (NEJM)', year: 2013 }],
  },
  {
    itemId: 'hyponatremia-1', version: 1, type: 'discriminator', conceptId: 'hyponatremia-approach',
    stem: 'A euvolemic patient has hyponatremia with a high urine osmolality, high urine sodium, and low serum uric acid — clinically not dehydrated or fluid-overloaded. Which mechanism?',
    vitals: [v('Na', '124', true)],
    findings: [],
    options: [
      { id: 'a', text: 'SIADH', correct: true },
      { id: 'b', text: 'Hypovolemic hyponatremia', whyNot: 'Volume depletion gives a LOW urine sodium as the kidney conserves salt; SIADH has a high urine sodium in a euvolemic patient.' },
      { id: 'c', text: 'Hypervolemic hyponatremia (heart failure/cirrhosis)', whyNot: 'Edematous states retain sodium avidly with low urine sodium; this patient is euvolemic with high urine sodium.' },
      { id: 'd', text: 'Psychogenic polydipsia', whyNot: 'Water intoxication dilutes the urine (low osmolality); SIADH inappropriately concentrates it.' },
    ],
    discriminator: 'Euvolemic hyponatremia with concentrated urine, high urine sodium and low uric acid is SIADH — volume status plus urine sodium/osmolality sort the causes of a low serum sodium.',
    tags: { system: 'multisystem', complaint: 'hyponatremia', rotation: ['im'], level: 'clerkship' },
    difficultySeed: 0.55, source: [{ ref: 'European Guideline on Diagnosis & Treatment of Hyponatraemia', year: 2014 }],
  },
  {
    itemId: 'vitamin-deficiency-1', version: 1, type: 'association', conceptId: 'vitamin-deficiency',
    stem: 'The triad of dermatitis, diarrhea and dementia (with a photosensitive "necklace" rash), classically from corn-based diets or isoniazid.',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Niacin (vitamin B3) deficiency — pellagra', correct: true },
      { id: 'b', text: 'Thiamine (B1) deficiency', whyNot: 'Thiamine deficiency causes Wernicke encephalopathy and beriberi, not the dermatitis-diarrhea-dementia triad.' },
      { id: 'c', text: 'Vitamin C deficiency', whyNot: 'Scurvy causes bleeding gums, perifollicular hemorrhage and poor healing, not the pellagra triad.' },
      { id: 'd', text: 'Vitamin B12 deficiency', whyNot: 'B12 deficiency gives macrocytic anemia and subacute combined degeneration, not photosensitive dermatitis with diarrhea.' },
    ],
    discriminator: 'The three Ds — dermatitis, diarrhea and dementia — with a photosensitive rash is pellagra from niacin deficiency, classically in corn-dependent diets, carcinoid, or isoniazid use.',
    tags: { system: 'multisystem', complaint: 'buzzword', rotation: ['im', 'fm'], level: 'both', boards: ['step1'] },
    difficultySeed: 0.5, source: [{ ref: 'WHO: Pellagra and its Prevention', year: 2000 }],
  },
  {
    itemId: 'geriatric-falls-1', version: 1, type: 'next_step', conceptId: 'geriatric-falls',
    stem: 'An 82-year-old on eight medications has had two recent falls. Beyond examining gait and vision, what is a high-yield first step?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Review and deprescribe medications that increase fall risk (sedatives, antihypertensives, anticholinergics)', correct: true },
      { id: 'b', text: 'Start a sedative-hypnotic to improve sleep', whyNot: 'Sedative-hypnotics markedly increase falls and fractures in elders — the opposite of what is needed.' },
      { id: 'c', text: 'Prescribe bed rest', whyNot: 'Immobility accelerates deconditioning and raises fall and pressure-injury risk; keep the patient active with gait training.' },
      { id: 'd', text: 'Order a head CT for everyone regardless of exam', whyNot: 'Imaging is guided by findings; the highest-yield modifiable factor here is polypharmacy.' },
    ],
    discriminator: 'Falls in an elder on many drugs demand a medication review — deprescribing sedatives, over-aggressive antihypertensives and anticholinergics is among the highest-yield fall-prevention steps.',
    tags: { system: 'multisystem', complaint: 'falls', rotation: ['fm', 'im'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'AGS/BGS Clinical Practice Guideline: Falls Prevention', year: 2011 }],
  },
  {
    itemId: 'cancer-screening-1', version: 1, type: 'tx_threshold', conceptId: 'cancer-screening',
    stem: 'At what age does routine colorectal cancer screening now begin for average-risk adults?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Age 45', correct: true },
      { id: 'b', text: 'Age 30', whyNot: 'That is too early for average risk; earlier screening is reserved for hereditary syndromes or a strong family history.' },
      { id: 'c', text: 'Age 60', whyNot: 'Starting at 60 misses a decade of preventable, screen-detectable disease.' },
      { id: 'd', text: 'Only if symptoms develop', whyNot: 'Screening is meant to catch disease before symptoms; waiting for symptoms defeats the purpose.' },
    ],
    discriminator: 'Average-risk colorectal cancer screening now begins at age 45 — earlier only with hereditary risk or family history; the aim is detection before symptoms.',
    teachingPoint: 'Other adult screens: mammography (biennial 50–74), cervical (21–65), low-dose CT for eligible smokers, and a one-time AAA ultrasound in men 65–75 who ever smoked.',
    tags: { system: 'multisystem', complaint: 'screening', rotation: ['fm', 'im'], level: 'clerkship' },
    difficultySeed: 0.55, source: [{ ref: 'USPSTF Recommendation: Colorectal Cancer Screening', year: 2021 }],
  },
  {
    itemId: 'inheritance-1', version: 1, type: 'discriminator', conceptId: 'inheritance-patterns',
    stem: 'A trait affects only males, is passed through unaffected carrier mothers, with no male-to-male transmission. Which inheritance pattern?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'X-linked recessive', correct: true },
      { id: 'b', text: 'Autosomal dominant', whyNot: 'Autosomal dominant affects both sexes with male-to-male transmission and a vertical pedigree.' },
      { id: 'c', text: 'Autosomal recessive', whyNot: 'AR affects both sexes equally and often skips generations with consanguinity, without the male-only, carrier-mother pattern.' },
      { id: 'd', text: 'Mitochondrial', whyNot: 'Mitochondrial inheritance passes only from mothers to ALL children of both sexes, not selectively to sons.' },
    ],
    discriminator: 'A disorder affecting males through carrier mothers with no male-to-male transmission is X-linked recessive — fathers cannot pass an X to sons, so the affected males cluster on the maternal line.',
    tags: { system: 'multisystem', complaint: 'genetics', rotation: ['peds', 'im'], level: 'both', boards: ['step1'] },
    difficultySeed: 0.55, source: [{ ref: 'Thompson & Thompson Genetics in Medicine', year: 2016 }],
  },

  /* ── Pediatrics ── */
  {
    itemId: 'croup-epiglottitis-1', version: 1, type: 'discriminator', conceptId: 'croup-vs-epiglottitis',
    stem: 'A child with fever and stridor. Which picture indicates epiglottitis rather than croup?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Rapid high fever, drooling, muffled voice and a tripod posture, looking toxic', correct: true },
      { id: 'b', text: 'A barking cough and inspiratory stridor after a few days of coryza', whyNot: 'A barking (seal-like) cough with a viral prodrome is croup, not the toxic, drooling picture of epiglottitis.' },
      { id: 'c', text: 'Steeple sign on a neck film', whyNot: 'Subglottic narrowing (steeple sign) is croup; epiglottitis shows a thumbprint sign.' },
      { id: 'd', text: 'Improvement with nebulised epinephrine and steroids', whyNot: 'That is the response of croup; epiglottitis is a surgical airway emergency, not managed with nebulisers alone.' },
    ],
    discriminator: 'Toxic, drooling, tripod-sitting with a muffled voice and no cough is epiglottitis (secure the airway, do not agitate); a barking cough with a viral prodrome and steeple sign is croup.',
    tags: { system: 'pediatrics', complaint: 'stridor', rotation: ['peds', 'em'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'AAP Clinical Guidance on Pediatric Airway Infections', year: 2021 }],
  },
  {
    itemId: 'bronchiolitis-1', version: 1, type: 'one_liner', conceptId: 'bronchiolitis',
    stem: 'A 6-month-old in winter with two days of coryza, now with wheeze, crackles, tachypnea and mild retractions after an RSV exposure.',
    vitals: [v('RR', '58', true), v('SpO₂', '93% RA', true)],
    findings: ['Diffuse wheeze and fine crackles; first episode of wheeze.'],
    options: [
      { id: 'a', text: 'Bronchiolitis', correct: true },
      { id: 'b', text: 'Asthma', whyNot: 'A first wheeze in an infant with a viral prodrome is bronchiolitis; asthma is diagnosed with recurrent episodes in older children.' },
      { id: 'c', text: 'Bacterial pneumonia', whyNot: 'Pneumonia gives focal consolidation and higher fever, not diffuse viral wheeze and crackles across both lungs.' },
      { id: 'd', text: 'Foreign body aspiration', whyNot: 'Aspiration causes sudden focal wheeze after choking, not a gradual viral coryza-to-wheeze course.' },
    ],
    discriminator: 'A first wheeze in an infant under 2 with a viral (RSV) prodrome and diffuse crackles/wheeze is bronchiolitis — largely supportive care; bronchodilators and antibiotics are not routinely helpful.',
    tags: { system: 'pediatrics', complaint: 'wheeze', rotation: ['peds', 'em'], level: 'both' },
    difficultySeed: 0.7, source: [{ ref: 'AAP Clinical Practice Guideline: Bronchiolitis', year: 2014 }],
  },
  {
    itemId: 'nrds-ttn-1', version: 1, type: 'discriminator', conceptId: 'nrds-vs-ttn',
    stem: 'A newborn has respiratory distress shortly after birth. Which detail favours respiratory distress syndrome (surfactant deficiency) over transient tachypnea?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Prematurity with a ground-glass, low-volume lung on X-ray', correct: true },
      { id: 'b', text: 'Term birth by cesarean with rapid improvement over a day', whyNot: 'That describes transient tachypnea of the newborn from retained fluid, which resolves quickly.' },
      { id: 'c', text: 'Fluid in the fissures on X-ray', whyNot: 'Interstitial fluid and fissural fluid are the TTN pattern, not the ground-glass atelectasis of surfactant deficiency.' },
      { id: 'd', text: 'Normal chest X-ray', whyNot: 'RDS shows diffuse ground-glass opacity with air bronchograms; a normal film argues against it.' },
    ],
    discriminator: 'A premature infant with ground-glass, low-volume lungs and worsening distress is surfactant-deficiency RDS; a term (often cesarean) baby with fluid in the fissures that clears in a day is transient tachypnea.',
    tags: { system: 'pediatrics', complaint: 'neonatal distress', rotation: ['peds'], level: 'both' },
    difficultySeed: 0.55, source: [{ ref: 'AAP Guidance on Respiratory Support in Preterm Infants', year: 2014 }],
  },
  {
    itemId: 'neonatal-jaundice-1', version: 1, type: 'cant_miss', conceptId: 'neonatal-jaundice',
    stem: 'A newborn is jaundiced. Which feature marks it as pathologic and needing urgent work-up rather than physiologic?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'Jaundice appearing in the first 24 hours of life', correct: true },
      { id: 'b', text: 'Jaundice appearing on day 3 and peaking at day 5', whyNot: 'That is the typical physiologic pattern in a well infant, resolving over the first week.' },
      { id: 'c', text: 'Mild jaundice in an otherwise well breastfed baby', whyNot: 'Breast-milk/breastfeeding jaundice is common and usually benign, not an emergency.' },
      { id: 'd', text: 'A total bilirubin that trends down after day 4', whyNot: 'A falling bilirubin after the physiologic peak is reassuring, not pathologic.' },
    ],
    discriminator: 'Jaundice in the first 24 hours (or a rapidly rising or conjugated bilirubin) is pathologic — think hemolysis or sepsis, and act to prevent kernicterus; day-2-to-3 onset in a well baby is usually physiologic.',
    tags: { system: 'pediatrics', complaint: 'jaundice', rotation: ['peds'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'AAP Clinical Practice Guideline: Hyperbilirubinemia', year: 2022 }],
  },
  {
    itemId: 'febrile-infant-1', version: 1, type: 'next_step', conceptId: 'febrile-infant',
    stem: 'A previously well 18-day-old has a rectal temperature of 38.2°C and looks well. What is the appropriate approach?',
    vitals: [v('T', '38.2', true)],
    findings: [],
    options: [
      { id: 'a', text: 'Full sepsis evaluation (blood, urine and CSF) with empiric antibiotics and admission', correct: true },
      { id: 'b', text: 'Reassure and discharge with antipyretics', whyNot: 'A febrile neonate cannot be cleared clinically; occult serious bacterial infection (including meningitis) requires a full work-up.' },
      { id: 'c', text: 'Oral antibiotics as an outpatient', whyNot: 'Neonatal fever needs cultures including CSF and IV empiric therapy, not empiric oral antibiotics at home.' },
      { id: 'd', text: 'Chest X-ray only', whyNot: 'A single film cannot exclude bacteremia or meningitis in this age group.' },
    ],
    discriminator: 'A fever in an infant under 28 days mandates a full sepsis work-up — including a lumbar puncture — with empiric antibiotics and admission, because well appearance does not exclude serious bacterial infection at this age.',
    tags: { system: 'pediatrics', complaint: 'fever', rotation: ['peds', 'em'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'AAP Clinical Practice Guideline: Febrile Infants 8–60 Days', year: 2021 }],
  },
  {
    itemId: 'milestones-1', version: 1, type: 'association', conceptId: 'developmental-milestones',
    stem: 'A typically developing infant who reciprocally social-smiles and coos — at approximately what age is this first expected?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'About 2 months', correct: true },
      { id: 'b', text: 'About 6 months', whyNot: 'By 6 months an infant sits with support and babbles; the social smile emerges much earlier, around 2 months.' },
      { id: 'c', text: 'About 9 months', whyNot: 'By 9 months an infant has stranger anxiety and a pincer grasp is developing; the social smile is far earlier.' },
      { id: 'd', text: 'About 12 months', whyNot: 'By 12 months a child says a first word and may walk; the social smile is a 2-month milestone.' },
    ],
    discriminator: 'The reciprocal social smile appears around 2 months — a key early social milestone; its absence by 2–3 months is a developmental red flag worth acting on.',
    tags: { system: 'pediatrics', complaint: 'development', rotation: ['peds', 'fm'], level: 'both', boards: ['step1', 'step2'] },
    difficultySeed: 0.6, source: [{ ref: 'CDC Developmental Milestones (Learn the Signs. Act Early.)', year: 2022 }],
  },
  {
    itemId: 'ductal-chd-1', version: 1, type: 'tx_next_step', conceptId: 'ductal-dependent-chd',
    stem: 'A neonate becomes severely cyanotic and shocked as the ductus arteriosus closes in the first days of life; a ductal-dependent congenital heart lesion is suspected. What drug maintains the circulation until surgery?',
    vitals: [v('SpO₂', '68%', true)],
    findings: [],
    options: [
      { id: 'a', text: 'Prostaglandin E1 (to keep the ductus open)', correct: true },
      { id: 'b', text: 'Indomethacin', whyNot: 'Indomethacin CLOSES the ductus — the opposite of what a ductal-dependent lesion needs.' },
      { id: 'c', text: 'High-dose oxygen alone', whyNot: 'Oxygen can hasten ductal closure and does not fix a duct-dependent mixing lesion; keep the duct open with prostaglandin.' },
      { id: 'd', text: 'Adenosine', whyNot: 'Adenosine treats SVT; it has no role in maintaining ductal patency.' },
    ],
    discriminator: 'A neonate who decompensates as the duct closes has a ductal-dependent lesion — start prostaglandin E1 to keep the ductus arteriosus open until definitive repair.',
    tags: { system: 'pediatrics', complaint: 'cyanosis', rotation: ['peds'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'AHA Scientific Statement: Neonatal Congenital Heart Disease', year: 2020 }],
  },
  {
    itemId: 'hirschsprung-1', version: 1, type: 'one_liner', conceptId: 'hirschsprung',
    stem: 'A full-term newborn fails to pass meconium in the first 48 hours and has abdominal distension; a rectal exam produces an explosive gush of stool.',
    vitals: [], findings: ['Contrast enema shows a transition zone; rectal biopsy shows absent ganglion cells.'],
    options: [
      { id: 'a', text: 'Hirschsprung disease', correct: true },
      { id: 'b', text: 'Meconium ileus', whyNot: 'Meconium ileus (often cystic fibrosis) obstructs with inspissated meconium but has normal ganglion cells on biopsy.' },
      { id: 'c', text: 'Anal atresia', whyNot: 'Anal atresia is an obvious absent or abnormal anal opening on exam, not aganglionosis with a patent anus.' },
      { id: 'd', text: 'Functional constipation', whyNot: 'Functional constipation does not present in the newborn with failure to pass meconium and absent ganglion cells.' },
    ],
    discriminator: 'Failure to pass meconium with distension, an explosive stool on rectal exam and absent ganglion cells on biopsy is Hirschsprung disease — an aganglionic segment that cannot relax.',
    tags: { system: 'pediatrics', complaint: 'no meconium', rotation: ['peds', 'surg'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'Nelson Textbook of Pediatrics', year: 2020 }],
  },
  {
    itemId: 'malrotation-1', version: 1, type: 'cant_miss', conceptId: 'malrotation-volvulus',
    stem: 'A previously well 3-week-old suddenly develops bilious vomiting and looks unwell. What must be excluded emergently?',
    vitals: [v('HR', '180', true)],
    findings: ['Abdomen initially soft; upper GI series shows an abnormal duodenal course.'],
    options: [
      { id: 'a', text: 'Malrotation with midgut volvulus', correct: true },
      { id: 'b', text: 'Gastroesophageal reflux', whyNot: 'Reflux is non-bilious effortless spit-up in a well baby, not bilious vomiting with an unwell infant.' },
      { id: 'c', text: 'Pyloric stenosis', whyNot: 'Pyloric stenosis causes NON-bilious projectile vomiting; bile means the obstruction is beyond the pylorus.' },
      { id: 'd', text: 'Overfeeding', whyNot: 'Overfeeding does not cause bilious vomiting with tachycardia and an abnormal duodenal course.' },
    ],
    discriminator: 'Bilious vomiting in a neonate is malrotation with midgut volvulus until excluded — a surgical emergency, because the twisted midgut can infarct within hours; get an urgent upper GI series.',
    tags: { system: 'pediatrics', complaint: 'bilious vomiting', rotation: ['peds', 'surg', 'em'], level: 'clerkship' },
    difficultySeed: 0.6, source: [{ ref: 'Nelson Textbook of Pediatrics', year: 2020 }],
  },
  {
    itemId: 'live-vaccine-ci-1', version: 1, type: 'tx_contraindication', conceptId: 'live-vaccine-contraindication',
    stem: 'For which patient is a live attenuated vaccine (e.g., MMR, varicella) contraindicated?',
    vitals: [], findings: [],
    options: [
      { id: 'a', text: 'A significantly immunocompromised patient (or pregnancy)', correct: true },
      { id: 'b', text: 'A child with a mild cold and low-grade fever', whyNot: 'Minor illness is not a contraindication; routine vaccination proceeds.' },
      { id: 'c', text: 'A child with a family history of vaccine reactions', whyNot: 'A family history is not a contraindication to the child\'s own vaccination.' },
      { id: 'd', text: 'A breastfeeding mother', whyNot: 'Breastfeeding is not a contraindication to live vaccines for the mother or infant.' },
    ],
    discriminator: 'Live attenuated vaccines are contraindicated in significant immunocompromise and in pregnancy, because the attenuated organism can cause disease in a host who cannot contain it — inactivated vaccines are safe.',
    tags: { system: 'pediatrics', complaint: 'immunization', rotation: ['peds', 'fm'], level: 'both' },
    difficultySeed: 0.6, source: [{ ref: 'CDC/ACIP General Best Practice Guidelines for Immunization', year: 2023 }],
  },
];

export const EXPANSION3: ContentModule = { concepts, subtopics, alsoSystems, items };
