/* One-shot migration reporter.

   In this codebase concepts already exist, so "migration" is the
   enrichment pass in content/bank.ts: every vignette is assigned to
   a concept, every concept is placed in the taxonomy, board/rotation/
   level tags are derived, and each vignette keeps `legacyItemId` so
   no learner state is orphaned. This script verifies that pass is
   lossless and writes MIGRATION_REPORT.md.

   Run: npm run migrate  */

import { writeFileSync } from 'node:fs';
import { CONCEPTS, ITEMS, servesBoard } from '../src/content/bank';
import { SUBTOPICS, TAXONOMY } from '../src/content/taxonomy';
import { validateBank } from '../src/content/validation';
import { UNREVIEWED } from '../src/types';

const { errors, warnings, stats } = validateBank(CONCEPTS, ITEMS);

const itemsPerConcept = new Map<string, number>();
for (const it of ITEMS) itemsPerConcept.set(it.conceptId, (itemsPerConcept.get(it.conceptId) ?? 0) + 1);

const orphanedVignettes = ITEMS.filter((i) => !i.legacyItemId).length;
const conceptsWithoutSubtopic = CONCEPTS.filter((c) => c.subtopic.endsWith('.UNMAPPED'));

// coverage: subtopics with ≥1 concept
const coveredSubtopics = new Set(CONCEPTS.map((c) => c.subtopic));
const emptySubtopics = SUBTOPICS.filter((s) => !coveredSubtopics.has(s.id));

const boardCounts = { step1: 0, step2: 0, step3: 0 } as Record<string, number>;
for (const it of ITEMS) for (const b of ['step1', 'step2', 'step3']) if (servesBoard(it, b as never)) boardCounts[b]++;

const lines: string[] = [];
lines.push('# MIGRATION REPORT — concept/taxonomy enrichment', '');
lines.push('*Generated by `npm run migrate`. Verifies the bank enrichment is lossless', 'and reports coverage against the taxonomy.*', '');
lines.push('## Census', '');
lines.push(`- Vignettes (items) in: **${stats.items}**`);
lines.push(`- Concepts out: **${stats.concepts}**`);
lines.push(`- Vignettes missing \`legacyItemId\` (orphan risk): **${orphanedVignettes}**`);
lines.push(`- Concepts not placed in the taxonomy: **${conceptsWithoutSubtopic.length}**${conceptsWithoutSubtopic.length ? ' — ' + conceptsWithoutSubtopic.map((c) => c.conceptId).join(', ') : ''}`);
lines.push(`- Concepts UNREVIEWED (pending physician sign-off): **${stats.unreviewed}/${stats.concepts}**`);
lines.push('');
lines.push('## Board-level distribution (vignettes; may serve several)', '');
lines.push(`- Step 1: ${boardCounts.step1} · Step 2 CK: ${boardCounts.step2} · Step 3: ${boardCounts.step3}`);
lines.push('');
lines.push('## Taxonomy coverage', '');
lines.push(`- Subtopics defined: **${SUBTOPICS.length}** across ${TAXONOMY.length} systems`);
lines.push(`- Subtopics with ≥1 concept: **${coveredSubtopics.size}**`);
lines.push(`- Empty subtopics (visible gaps to fill): **${emptySubtopics.length}**`);
lines.push('');
lines.push('### Empty subtopics by system', '');
for (const sys of TAXONOMY) {
  const empties = sys.subtopics.filter((s) => !coveredSubtopics.has(s.id));
  if (empties.length === 0) continue;
  lines.push(`- **${sys.name}**: ${empties.map((s) => s.id).join(', ')}`);
}
lines.push('');
lines.push('## Validation', '');
lines.push(`- Errors: **${errors.length}**${errors.length ? '\n' + errors.map((e) => `  - ${e}`).join('\n') : ''}`);
lines.push(`- Warnings: **${warnings.length}**`);
lines.push('');
lines.push('---', `_Every concept is currently marked ${UNREVIEWED}. Sources are cited on every`, 'vignette, but no concept has yet had physician review. Do not present this', 'content to a learner as validated._', '');

writeFileSync(new URL('../MIGRATION_REPORT.md', import.meta.url), lines.join('\n'));

console.log(`items in: ${stats.items}  concepts out: ${stats.concepts}  unmapped: ${conceptsWithoutSubtopic.length}  orphaned: ${orphanedVignettes}`);
console.log(`taxonomy: ${coveredSubtopics.size}/${SUBTOPICS.length} subtopics covered, ${emptySubtopics.length} empty`);
console.log(errors.length ? `✗ ${errors.length} validation errors` : '✓ enrichment lossless, no errors');
if (errors.length) process.exit(1);
